### ISSUE TITLE
Issues with auto-scroll on low-width devices

### ISSUE THREAD

**Issue by anoopsethu** [isaacplmann/ngx-tour#100]
Was developing the tour(MdMenu version) for devices with low screen width (<800px). The tour pop-ups at times go beyond the viewport and the auto-scroll doesn't happen. This kind of breaks the experience. Is there a fix to this?

**Comment by isaacplmann** [comment]
It should autoscroll to the `tourAnchor` element and then open the tour step based on the space available in the viewport.  Is the autoscroll not happening at all?  Or is the tour step opening outside of the viewport?

What browser/device is not working for you?
