### ISSUE TITLE
ERROR Error: No provider for Router!

### ISSUE THREAD

**Issue by pnagar1705** [isaacplmann/ngx-tour#101]
Hi, I am trying to follow steps from the documentation
https://isaacplmann.github.io/ngx-tour/
I have the following configurations done so far. I am trying to create a tour for Mycomponent class which is not on the root .
On app.module

`import { RouterModule } from '@angular/router';
import { TourMatMenuModule } from 'ngx-tour-md-menu';`

`@NgModule({....
TourMatMenuModule.forRoot(),
        RouterModule.forChild([{
           component:EditOrganizationDialogComponent,
           path:''
       }])`

Inside EditOrganizationDialogComponent
`import { TourService } from 'ngx-tour-md-menu';`
and added the following on the constructor
`constructor(...,
                public tourService: TourService) {

        this.tourService.initialize([{
            anchorId: 'some.anchor.id1',
            content: 'Welcome to the Ngx-Tour tour!',
            placement: 'below',
            title: 'Welcome',
        }],{
            route: '',
        });

        this.tourService.start();
    }
`

FOr the template: I added the following on the root level html 
`<tour-step-template></tour-step-template>`

But when I am trying to load that component, I am getting the following injection error 
EditOrganizationDialogComponent_Host.html:1 ERROR Error: No provider for Router!
    at injectionError (core.es5.js?de3d:1169)
    at noProviderError (core.es5.js?de3d:1207)
    at ReflectiveInjector_._throwOrNull (core.es5.js?de3d:2649)
    at ReflectiveInjector_._getByKeyDefault (core.es5.js?de3d:2688)
    at ReflectiveInjector_._getByKey (core.es5.js?de3d:2620)
    at ReflectiveInjector_.get (core.es5.js?de3d:2489)
    at resolveNgModuleDep (core.es5.js?de3d:9489)
    at _createClass (core.es5.js?de3d:9528)
    at _createProviderInstance$1 (core.es5.js?de3d:9500)
    at resolveNgModuleDep (core.es5.js?de3d:9485)

**Comment by isaacplmann** [comment]
`RouterModule.forChild([])` doesn't provide the `Router` for you.  You need `RouterModule.forRoot([])`.

**Comment by pnagar1705** [comment]
Thanks for your prompt repsonse. That error is gone but now I am getting the following error
zone.js?03a0:679 Unhandled Promise rejection: Invalid configuration of route '': routes must have either a path or a matcher specified ; Zone: <root> ; Task: Promise.then ; Value: Error: Invalid configuration of route '': routes must have either a path or a matcher specified
    at validateNode (router.es5.js?e685:485)
    at validateConfig (router.es5.js?e685:448)
    at Router.resetConfig (router.es5.js?e685:3790)
    at new Router (router.es5.js?e685:3695)
    at setupRouter (router.es5.js?e685:6069)
    at _callFactory (core.es5.js?de3d:9574)
    at _createProviderInstance$1 (core.es5.js?de3d:9503)
    at initNgModule (core.es5.js?de3d:9454)
    at new NgModuleRef_ (core.es5.js?de3d:10568)
    at createNgModuleRef (core.es5.js?de3d:10552) Error: Invalid configuration of route '': routes must have either a path or a matcher specified
    at validateNode (webpack-internal:///./node_modules/@angular/router/@angular/router.es5.js:581:15)
    at validateConfig (webpack-internal:///./node_modules/@angular/router/@angular/router.es5.js:544:9)
    at Router.resetConfig (webpack-internal:///./node_modules/@angular/router/@angular/router.es5.js:3886:9)
    at new Router (webpack-internal:///./node_modules/@angular/router/@angular/router.es5.js:3791:14)
    at setupRouter (webpack-internal:///./node_modules/@angular/router/@angular/router.es5.js:6165:35)
    at _callFactory (webpack-internal:///./node_modules/@angular/core/@angular/core.es5.js:9778:34)
    at _createProviderInstance$1 (webpack-internal:///./node_modules/@angular/core/@angular/core.es5.js:9707:26)
    at initNgModule (webpack-internal:///./node_modules/@angular/core/@angular/core.es5.js:9658:13)
    at new NgModuleRef_ (webpack-internal:///./node_modules/@angular/core/@angular/core.es5.js:10772:9)
    at createNgModuleRef (webpack-internal:///./node_modules/@angular/core/@angular/core.es5.js:10756:12)
api.onUnhandledError @ zone.js?03a0:679
handleUnhandledRejection @ zone.js?03a0:706
_loop_1 @ zone.js?03a0:696
api.microtaskDrainDone @ zone.js?03a0:700
drainMicroTaskQueue @ zone.js?03a0:610
ZoneTask.invokeTask @ zone.js?03a0:503
ZoneTask.invoke @ zone.js?03a0:488
timer @ zone.js?03a0:2007
setTimeout (async)
scheduleTask @ zone.js?03a0:2023
ZoneDelegate.scheduleTask @ zone.js?03a0:411
Zone.scheduleTask @ zone.js?03a0:236
Zone.scheduleMacroTask @ zone.js?03a0:259
(anonymous) @ zone.js?03a0:2039
proto.(anonymous function) @ zone.js?03a0:1355
(anonymous) @ jquery.js?eedf:3676
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
fire @ jquery.js?eedf:3443
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
mightThrow @ jquery.js?eedf:3629
process @ jquery.js?eedf:3638
ZoneDelegate.invokeTask @ zone.js?03a0:425
Zone.runTask @ zone.js?03a0:192
ZoneTask.invokeTask @ zone.js?03a0:499
ZoneTask.invoke @ zone.js?03a0:488
timer @ zone.js?03a0:2007
setTimeout (async)
scheduleTask @ zone.js?03a0:2023
ZoneDelegate.scheduleTask @ zone.js?03a0:411
Zone.scheduleTask @ zone.js?03a0:236
Zone.scheduleMacroTask @ zone.js?03a0:259
(anonymous) @ zone.js?03a0:2039
proto.(anonymous function) @ zone.js?03a0:1355
(anonymous) @ jquery.js?eedf:3676
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
fire @ jquery.js?eedf:3443
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
mightThrow @ jquery.js?eedf:3629
process @ jquery.js?eedf:3638
ZoneDelegate.invokeTask @ zone.js?03a0:425
Zone.runTask @ zone.js?03a0:192
ZoneTask.invokeTask @ zone.js?03a0:499
ZoneTask.invoke @ zone.js?03a0:488
timer @ zone.js?03a0:2007
setTimeout (async)
scheduleTask @ zone.js?03a0:2023
ZoneDelegate.scheduleTask @ zone.js?03a0:411
Zone.scheduleTask @ zone.js?03a0:236
Zone.scheduleMacroTask @ zone.js?03a0:259
(anonymous) @ zone.js?03a0:2039
proto.(anonymous function) @ zone.js?03a0:1355
(anonymous) @ jquery.js?eedf:3676
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
fire @ jquery.js?eedf:3443
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
mightThrow @ jquery.js?eedf:3629
process @ jquery.js?eedf:3638
ZoneDelegate.invokeTask @ zone.js?03a0:425
Zone.runTask @ zone.js?03a0:192
ZoneTask.invokeTask @ zone.js?03a0:499
ZoneTask.invoke @ zone.js?03a0:488
timer @ zone.js?03a0:2007
setTimeout (async)
scheduleTask @ zone.js?03a0:2023
ZoneDelegate.scheduleTask @ zone.js?03a0:411
Zone.scheduleTask @ zone.js?03a0:236
Zone.scheduleMacroTask @ zone.js?03a0:259
(anonymous) @ zone.js?03a0:2039
proto.(anonymous function) @ zone.js?03a0:1355
(anonymous) @ jquery.js?eedf:3676
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
fire @ jquery.js?eedf:3443
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
done @ jquery.js?eedf:9242
(anonymous) @ jquery.js?eedf:9484
wrapFn @ zone.js?03a0:1155
ZoneDelegate.invokeTask @ zone.js?03a0:425
Zone.runTask @ zone.js?03a0:192
ZoneTask.invokeTask @ zone.js?03a0:499
invokeTask @ zone.js?03a0:1509
globalZoneAwareCallback @ zone.js?03a0:1535
error (async)
customScheduleGlobal @ zone.js?03a0:1635
ZoneDelegate.scheduleTask @ zone.js?03a0:411
Zone.scheduleTask @ zone.js?03a0:236
Zone.scheduleEventTask @ zone.js?03a0:262
(anonymous) @ zone.js?03a0:1800
desc.set @ zone.js?03a0:1205
send @ jquery.js?eedf:9504
ajax @ jquery.js?eedf:9143
jQuery.(anonymous function) @ jquery.js?eedf:9292
UserSettingsLoader.getUserSettings @ user-settings-loader.ts?f1df:38
(anonymous) @ main.ts?e25b:44
mightThrow @ jquery.js?eedf:3570
process @ jquery.js?eedf:3638
ZoneDelegate.invokeTask @ zone.js?03a0:425
Zone.runTask @ zone.js?03a0:192
ZoneTask.invokeTask @ zone.js?03a0:499
ZoneTask.invoke @ zone.js?03a0:488
timer @ zone.js?03a0:2007
setTimeout (async)
scheduleTask @ zone.js?03a0:2023
ZoneDelegate.scheduleTask @ zone.js?03a0:411
Zone.scheduleTask @ zone.js?03a0:236
Zone.scheduleMacroTask @ zone.js?03a0:259
(anonymous) @ zone.js?03a0:2039
proto.(anonymous function) @ zone.js?03a0:1355
(anonymous) @ jquery.js?eedf:3676
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
fire @ jquery.js?eedf:3443
fire @ jquery.js?eedf:3305
fireWith @ jquery.js?eedf:3435
done @ jquery.js?eedf:9242
(anonymous) @ jquery.js?eedf:9484
wrapFn @ zone.js?03a0:1155
ZoneDelegate.invokeTask @ zone.js?03a0:425
Zone.runTask @ zone.js?03a0:192
ZoneTask.invokeTask @ zone.js?03a0:499
invokeTask @ zone.js?03a0:1509
globalZoneAwareCallback @ zone.js?03a0:1535
error (async)
customScheduleGlobal @ zone.js?03a0:1635
ZoneDelegate.scheduleTask @ zone.js?03a0:411
Zone.scheduleTask @ zone.js?03a0:236
Zone.scheduleEventTask @ zone.js?03a0:262
(anonymous) @ zone.js?03a0:1800
desc.set @ zone.js?03a0:1205
send @ jquery.js?eedf:9504
ajax @ jquery.js?eedf:9143
jQuery.(anonymous function) @ jquery.js?eedf:9292
getJSON @ jquery.js?eedf:9273
(anonymous) @ main.ts?e25b:32
(anonymous) @ main.ts:47
./node_modules/ls-shell/ui/main.ts @ bundle.js:2369
__webpack_require__ @ manifest.js:704
fn @ manifest.js:117
0 @ bundle.js:5032
__webpack_require__ @ manifest.js:704
webpackJsonpCallback @ manifest.js:26
(anonymous) @ bundle.js:1
client.js?3ac5:87 

and my route is empty as indicated above. What value goes in the route?

**Comment by pnagar1705** [comment]
Also , I forgot to mention, I also have the following to my providers []
`TourMatMenuModule.forRoot().providers`

**Comment by pnagar1705** [comment]
I also tried giving a selector in the route property: `route: 'app-organization-details',` in my components constructor

**Comment by isaacplmann** [comment]
Just use `RouterModule.forRoot([])` with no routes if you don't want to use the router.

**Comment by pnagar1705** [comment]
It gives me the same error

**Comment by pnagar1705** [comment]
My application does not use RouterModule. and therefore not able to use the Tour Service. We are using UIRouter

**Comment by raoulsigne** [comment]
Hi @pnagar1705 if you have not yet figured out your problem here is the answer

You should add this at the @Component of your page

 providers: [TourService],
