### ISSUE TITLE
Getting error "Cannot read property 'listen' of undefined at TransitionAnimationEngine.listen"

### ISSUE THREAD

**Issue by islam56naser** [isaacplmann/ngx-tour#102]
## Hi, I'm getting this error when calling tour service start method
I'm initializing the service in a lazy loaded module with anchors located in other modules like this

```
this.tourService.initialize([
      {
        anchorId: 'vehicle.start',
        content: 'Some content',
        title: 'First',
        route: '/resources/vehicle/new'

      },
      {
        anchorId: 'worker.start',
        content: 'Other content',
        title: 'Second',
        route: '/resources/manpower/new'

      },
      {
        anchorId: 'job.start',
        content: 'Other content',
        title: 'Third',
        route: '/jobs/new'

      }
    ]);
```

I've also subscribed to the events$ observable on the service which fired a "start" event and three "anchorRegister" events as expected.  

This is the complete error I get 
**ERROR TypeError: Cannot read property 'listen' of undefined
    at TransitionAnimationEngine.listen (browser.js:4251)
    at InjectableAnimationEngine.AnimationEngine.listen (browser.js:5626)
    at AnimationRenderer.listen (animations.js:720)
    at DebugRenderer2.listen (core.js:15428)
    at listenToElementOutputs (core.js:10571)
    at createViewNodes (core.js:13704)
    at createEmbeddedView (core.js:13614)
    at callWithDebugContext (core.js:15051)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (core.js:14363)
    at TemplateRef_.createEmbeddedView (core.js:11689)**

**Comment by isaacplmann** [comment]
Try updating all the `@angular` packages to the latest version.  (At the minimum they all need to be the same version.)  Except for `@angular/cdk` and `@angular/material` which need to match each other, but aren't in sync with the other `@angular` packages.

You can do this automatically from the command line by running `npm update` in the project directory.

**Comment by islam56naser** [comment]
I ran an npm update and I still have the same issue. right now I'm using these versions
```
    @angular/cdk: "^5.2.4",
    @angular/core": "^5.2.9",
```

**Comment by isaacplmann** [comment]
Are you using `@angular/animations` in any other parts of your app?  i.e. using another ui library like material that leverages the animations?

The error seems to be coming from the animations library, but I've never seen it before and I'm not sure what could be causing it.  The problem might be in how you are importing the various modules.

**Comment by islam56naser** [comment]
There is a library for toasts  `angular2-notifications` that I'm importing in the root module that depends on `animations`.
Here is my root module imports
```
 imports: [
    BrowserModule,
    BrowserAnimationsModule,    
    SharedModule.forRoot(),
    SimpleNotificationsModule.forRoot(),
    TourMatMenuModule.forRoot()
  ]
```

**Comment by isaacplmann** [comment]
I'm sorry, I'm out of ideas.  Those imports look right.

**Comment by islam56naser** [comment]
Thanks @isaacplmann, I've found the solution for this issue. The problem was that I didn't  include the `<tour-step-template></tour-step-template>` in the component I'm routing to. The error was really misleading.

**Comment by imHarshBhatia** [comment]
> Thanks @isaacplmann, I've found the solution for this issue. The problem was that I didn't include the `<tour-step-template></tour-step-template>` in the component I'm routing to. The error was really misleading.

You are right @islam56naser. It works. :)

**Comment by Stusaw** [comment]
For anyone still facing this issue the important part is that include the `<tour-step-template></tour-step-template>` in the lazy module component. The documentation just suggests that it is only needed in the app.component.ts
