### ISSUE TITLE
Delay until anchor registers

### ISSUE THREAD

**Issue by bluefire2121** [isaacplmann/ngx-tour#103]
This isn't an issue. I'm just looking for help. When using **ngx-tour-md-menu** how do I delay a step until after a component renders its anchors? I have tour that starts within a single component, then uses a step object's route property to route to a sister component. The sister component uses lazy loading. As I have it today, the tour step can't find the next anchor since it's looking for it before the sister component finishes loading. 

What can I do to delay a step until the route has render its anchors?

**Comment by isaacplmann** [comment]
There isn't a good way to do that right now.

It would be a nice feature to add a "wait until registered" fallback in the TourService if it tries to open an anchor that doesn't exist.  It would look for the anchor, and if it can't find it subscribe to the anchorRegister$ observable and then proceed once the step has been registered.

Want to submit a PR?  I'll coach you through it.

**Comment by bluefire2121** [comment]
Great idea @isaacplmann . I'll submit a PR and follow your suggestion.

**Comment by isaacplmann** [comment]
@Panduss I'd be happy to help you make a PR.

Or you could listen to the `anchorRegister$` observable and only start the tour once the first anchor has been registered.
