### ISSUE TITLE
Is there an implementation or a way to make "backdrop" css effect?

### ISSUE THREAD

**Issue by fakedestinyck** [isaacplmann/ngx-tour#104]
Hi,

I'm using `ngx-tour-ng-bootstrap` and want to figure out if there's any solution to make a **backdrop** css effect.

I've checked some current issues like #61 and #97 , but I found neither the class `.cdk-overlay-backdrop` nor `.cdk-overlay-transparent-backdrop` that you mentioned, exists when I view properties in the browser.

Since I'm really new to Angular, did I missed something, or how can I make it?

Thank you!

**Comment by isaacplmann** [comment]
You didn't miss anything.  `ngx-tour` isn't in charge of the ui piece, so whatever `ng-bootstrap` offers is what `ngx-tour-ng-bootstrap` offers.  From their [popover](https://ng-bootstrap.github.io/#/components/popover/examples) documentation, it looks like they do not provide backdrop support.  You could [file an issue](https://github.com/ng-bootstrap/ng-bootstrap/issues) with them.

**Comment by fakedestinyck** [comment]
@isaacplmann All right, thank you!

**Comment by suparnavg** [comment]
If you're using ngx-bootstrap as the external library, I managed to get this effect working by adding a modal div inside the component.html where the tour is displayed, and by setting appropriate right z-index, background colour and opacity values. The visibility of this div is toggled based one the `tourService.start` and `tourService.end` events. Finally, to make the element to which the popover is attached visible on "top" of the backdrop, set a higher z-index to the `touranchor--is-active` class and you should be good to go!

**Comment by thari119** [comment]
touranchor--is-active this isn't been show anywhere ?? can provide an example of this?

**Comment by dws-tushargupta** [comment]
> If you're using ngx-bootstrap as the external library, I managed to get this effect working by adding a div inside the component.html where the tour is displayed, and by setting appropriate right z-index, background colour and opacity values. The visibility of this div is toggled based one the `tourService.start` and `tourService.end` events. Finally, to make the element to which the popover is attached visible on "top" of the backdrop, set a higher z-index to the `touranchor--is-active` class and you should be good to go!

R U saying, something like this?
```// for ngx-tour
.touranchor--is-active {
  position: relative;
  background: #fff; //for highlighting inline elements
  z-index: 1001	; //optional
}

.cdk-overlay-transparent-backdrop {
  background: black;
}

touranchoropener {
  display: none; //this opener element occupies space , so inline elements got disturbed
}```
