### ISSUE TITLE
How to highlight anchor is being activated

### ISSUE THREAD

**Issue by quoctu2016** [isaacplmann/ngx-tour#106]
I can't use class .touranchor--is-active

**Comment by isaacplmann** [comment]
That's the best you can do right now.

**Comment by isaacplmann** [comment]
Check out ngx-tour-md-menu@3.1.0

**Comment by thari119** [comment]
i'm using ngx-tour-ngx-bootstrap module but my tour anchors dont have the class .touranchor--is-active? any idea why?

**Comment by isaacplmann** [comment]
@thari119 no, I'm not sure.  Is the component with the anchor using OnPush change detection?

**Comment by dws-tushargupta** [comment]
Hi quoctu2016,
For highlighting the inline elements(like anchor tags), you have to use a class in your global styles.scss file.
Please give underneath a try:
```
.touranchor--is-active {
  position: relative;
  background: #fff;   //for highlighting inline elements
  z-index: 1001;   //optional
}
```
