### ISSUE TITLE
Backdrop Support

### ISSUE THREAD

**Issue by Santhosh25** [isaacplmann/ngx-tour#11]
Is ng2-tour support backdrop functionality? If yes, please let me know how can i enable it?

**Comment by isaacplmann** [comment]
`ng2-tour` uses the `popover`s from `@ng-bootstrap/ng-bootstrap`.  It can do [everything they can](https://ng-bootstrap.github.io/#/components/popover).  It looks like the answer is no.

However, the `ng2-tour` display functionality is completely separated from the tour logic, so if you find another library that provides popovers/popups with a backdrop, it should be pretty straightforward to create a separate module (modeled on Ng2TourBootstrapModule) that displays the popups from the other library.  Someday, I plan to get around to documenting how to do that.

**Comment by Santhosh25** [comment]
Thanks for the reply @isaacplmann . Is there any feature plan to add backdrop functionality like angular-ui-tour plugin did?

**Comment by isaacplmann** [comment]
Backdrop support is not something this library is in control of.  You can
file an issue with ng-bootstrap or find another library that creates
popovers with a backdrop.

**Comment by Santhosh25** [comment]
cool buddy and thank you for quick reply.

**Comment by isaacplmann** [comment]
`ngx-tour-md-menu@1.x` has backdrop support, if you're still looking for a solution.
