### ISSUE TITLE
Prevent popup from closing when you click outside

### ISSUE THREAD

**Issue by stanleynik** [isaacplmann/ngx-tour#110]
This is not an issue but I need help with this

**Comment by isaacplmann** [comment]
What ui plugin are you using?  `ngx-tour-md-menu`, `ngx-tour-ng-bootstrap` or `ngx-tour-ngx-bootstrap`?

**Comment by stanleynik** [comment]
Also it seems that the popup is blocking the other document elements. Because of this I need to double click in the purple box below to make it works
I guess this is the default behavior but how can avoid this?

![image](https://user-images.githubusercontent.com/1819814/39259806-b0cfba0a-4874-11e8-86b9-9fb3b4144758.png)

I appreciate your help with this

**Comment by stanleynik** [comment]
It works! 
Thanks
