### ISSUE TITLE
compilation error on adding this module

### ISSUE THREAD

**Issue by moxda** [isaacplmann/ngx-tour#113]
ERROR in node_modules/@angular/material/stepper/typings/stepper.d.ts(28,5): error TS2416: Property '_stepHeader' in type 'MatStepper' is not assignable to the same property in base type 'CdkStepper'.
  Type 'QueryList<ElementRef>' is not assignable to type 'QueryList<FocusableOption>'.
    Type 'ElementRef' is not assignable to type 'FocusableOption'.
      Property 'focus' is missing in type 'ElementRef'.

**Comment by isaacplmann** [comment]
We don't use a matstepper anywhere in the library.
