### ISSUE TITLE
ng-bootstrap 2.0.0 compatibility for Angular 6 upgrade

### ISSUE THREAD

**Issue by fijas** [isaacplmann/ngx-tour#114]
ng-bootstrap `2.0.0` is released to be compatible with Angular 6. But `ngx-tour-ng-bootstrap` depends on `^1.0.0`. Would it be possible to bump version as I am not able to upgrade to Angular 6 because of this?

**Comment by bluefire2121** [comment]
See #115

**Comment by isaacplmann** [comment]
`ngx-tour-ng-bootstrap@3.0.0` supports ng-bootstrap `2.0.0`
