### ISSUE TITLE
RxJS 6 compatibility issue: 'mergeStatic' was not found in 'rxjs/operator/merge'

### ISSUE THREAD

**Issue by halilibrahim** [isaacplmann/ngx-tour#115]
Can you please update RxJS dependency to v6?

I'm trying to update my application to RxJS 6 and getting 'mergeStatic' was not found in 'rxjs/operator/merge' error on:
https://github.com/isaacplmann/ngx-tour/blob/37ed37c59ca0182fdd7d2fc382898f007a2a02a7/ngx-tour-core/src/tour.service.ts#L8

https://github.com/isaacplmann/ngx-tour/blob/37ed37c59ca0182fdd7d2fc382898f007a2a02a7/ngx-tour-core/src/tour.service.ts#L46

You can see the error on console of [reproduction repo](https://stackblitz.com/edit/angular-ngx-tour-issue-115?file=src%2Fapp%2Fapp.module.ts).

Related [stackoverflow answer](https://stackoverflow.com/a/50062096/2215563).

**Comment by bluefire2121** [comment]
RxJS libraries have changed. Here's how to fix them: https://www.academind.com/learn/javascript/rxjs-6-what-changed/

You can make RxJS backwards compatible by following the migration instructions and installing rxjs-compat. Check the repo.

**Comment by LPCmedia** [comment]
try this fork as a workaround. some minor issue on the material version that I may or probably wont fix. 
https://github.com/LPCmedia/ngx-tour

**Comment by isaacplmann** [comment]
Thanks for PR #116, @LPCmedia .  I'll merge this today or tomorrow.

**Comment by elenafedorets** [comment]
@isaacplmann can you please merge PR #116? I have some trouble and I hope it will fix it

**Comment by codebreach** [comment]
@isaacplmann any ETA on the merge?

**Comment by isaacplmann** [comment]
It was more than just a merge, but `3.0.0` versions of all the libraries have been published with Angular 6/rxjs 6 support.

**Comment by halilibrahim** [comment]
Thanks @isaacplmann
