### ISSUE TITLE
Not supporting older Angular material version

### ISSUE THREAD

**Issue by sandraandonov88** [isaacplmann/ngx-tour#117]
Hi, I am trying to use ngx-tour with Angular Material 2.0.0-beta.11, but I am getting the following error on application startup:

zone.js?6524:672 Unhandled Promise rejection: The "mat-" prefix cannot be used in ng-material v1 compatibility mode. It was used on an "mat-menu" element. ; Zone: <root> ; Task: Promise.then ; Value: Error: The "mat-" prefix cannot be used in ng-material v1 compatibility mode. It was used on an "mat-menu" element.

Updating to the latest version of Angular Material is not an option for us currently.

**Comment by isaacplmann** [comment]
Try [version 1.0.4](https://github.com/isaacplmann/ngx-tour/blob/master/projects/ngx-tour-md-menu/CHANGELOG.md#104-2017-08-30)

**Comment by sandraandonov88** [comment]
I ended up using the ngx-popper version of the ngx-tour package, so I won't be able to try with version 1.0.4. @isaacplmann please feel free to close this issue. Thanks

**Comment by sandraandonov88** [comment]
@isaacplmann - I just upgraded to angular 6 and started getting error from the NgxTourService. Does the package support angular v6? I can share the specific error if necessary. Thanks

**Comment by isaacplmann** [comment]
Yes, please share the error. Others are having issues as well. I'll be on
vacation until Thursday and take a look then.

**Comment by georgiaabarnes** [comment]
I was able to get ngx-tour-ngx-popper to work when I changed line 17 in node_modules/ngx-tour-ngx-popper/ngx-tour-ngx-popper.es5.js to:

`import { merge as mergeStatic} from 'rxjs/observable/merge';`

@isaacplmann it seems like you made this change in ngx-tour but not all the other versions

**Comment by georgiaabarnes** [comment]
It also seems that rxjs 6 depreciated observable.prototype, but it seems like this package will make rxjs backwards compatible: [https://www.npmjs.com/package/rxjs-compat](url)
