### ISSUE TITLE
how to implement TourService

### ISSUE THREAD

**Issue by pedroskakum** [isaacplmann/ngx-tour#119]
i don't have ideia:

`
import { Component, OnInit } from '@angular/core'
import { TourService } from 'ngx-tour-core';

@Component({
    selector: 'app-panel',
    templateUrl: './panel.component.html'
})

export class PanelComponent implements OnInit, TourService {

    router
    constructor() {
        tourService.initialize([{
            anchorId: 'perfil.completo',
            content: 'lorem ipsum dolor sit amet consectetur adipiscing elit',
            title: 'Aqui voce pode ver o Perfil completo',
        }, {
            anchorId: 'another.anchor.id',
            content: 'Other content',
            title: 'Second',
        }]);
    }

    ngOnInit() {
        tourService.start()
    }
}
`

i have error:

`
ERROR in src/app/@nagro/dashboard/panel/panel.component.ts(9,14): error TS2420: Class 'PanelComponent' incorrectly implements interface 'TourService<IStepOption>'.
  Property 'router' is private in type 'TourService<IStepOption>' but not in type 'PanelComponent'.
src/app/@nagro/dashboard/panel/panel.component.ts(13,9): error TS2304: Cannot find name 'tourService'.
src/app/@nagro/dashboard/panel/panel.component.ts(25,9): error TS2304: Cannot find name 'tourService'.
`

**Comment by rubenheymans** [comment]
This is my code:

```
  constructor(
    private ts: TourService
  ) {

    this.ts.initialize([
      {
        anchorId: 'some.anchor.id',
        content: 'Some content',
        title: 'First',
        route: '/',
      },
      {
        anchorId: 'another.anchor.id',
        content: 'Other content',
        title: 'Second',
        route: '/',
      },
      {
        anchorId: 'third.anchor.id',
        content: 'Other page content',
        title: 'Third',
        route: '/geschiedenis',
      },
    ]);

  }

  public startTour() {
    this.ts.start();
  }
```

I don't think you need to implement it here: `export class PanelComponent implements OnInit, TourService {`

You can check the [demo](https://github.com/isaacplmann/ngx-tour/blob/master/src/app/md-menu/md-menu.component.ts)

**Comment by isaacplmann** [comment]
Thanks, @rubenheymans . That's what I would recommend too.
