### ISSUE TITLE
ngx-tour unable to choose correct module

### ISSUE THREAD

**Issue by Eralmidia** [isaacplmann/ngx-tour#121]
I just testet the ngx-tour for the first time, and it seems to have a problem determining the module.

In my app module routing, I have the following three lazy loaded main modules:
![image](https://user-images.githubusercontent.com/12936286/41220037-605b2828-6d60-11e8-95d7-0bb9230688fd.png)

In the control panel module routing:
![image](https://user-images.githubusercontent.com/12936286/41220132-a9622cb0-6d60-11e8-90a0-eee06feef75b.png)

Now, I would like to make a tour of the trigger-and-automation module, so I define the following steps in my app.component:
![image](https://user-images.githubusercontent.com/12936286/41220741-9a01c940-6d62-11e8-99bc-4c928b808bcf.png)

When navigating to control-panel/trigger-and-automation, this works fine. However, if I navigate to control-panel/users, I am automatically redirected to control-panel/trigger-and-automation and the tour starts. Why doesn't ngx-tour recognize that users and trigger-and-automation are two different modules?

**Comment by isaacplmann** [comment]
`this._tourService.start()` is telling the tour to start and go to the first defined step.  If you only want that to happen when the user goes to the `control-panel/trigger-and-animation` route, you should remove that line of code from `app.component.ts` and put it in the `trigger-and-animation` component.

**Comment by Eralmidia** [comment]
Ok, thanks. That was kinda what I was thinking too, but the instructions for lazy loaded modules was pretty clear:

Start the tour with
tourService.start()
in **the same** component you initialized your steps. Call this right after the initialization.

**Comment by isaacplmann** [comment]
If you want to have different steps in `control-panel/users`, then you will need to `initialize` again in that component and call `start` after you `initialize`.

**Comment by Eralmidia** [comment]
So you cannot define all steps in a separate component, and initialize there, and then use the startAt method for the different modules?

**Comment by isaacplmann** [comment]
Yes, you could use `startAt` for that purpose.  Then the user can browse through all the steps in your whole app.
