### ISSUE TITLE
Placement TourMatMenuModule

### ISSUE THREAD

**Issue by bluefire2121** [isaacplmann/ngx-tour#122]
Since there isn't a placement in TourMatMenuModule, is there any other way to control where the tour card appears on the screen? I'd like to place it to the left or right of certain element tour anchors. Tried using SCSS styles, but it looks like the position of the card is determined by a script which overrides even !important modifiers.

**Comment by bluefire2121** [comment]
I was able to figure this out. I just had to really stretch those CSS classes.

**Comment by aniket-02** [comment]
@bluefire2121 could you please help me out how you figured this out...
