### ISSUE TITLE
Using ngx-tour in Angular 6 projects

### ISSUE THREAD

**Issue by pranavjain** [isaacplmann/ngx-tour#124]
Could someone guide me on using this library via npm? I find that there are multiple npm packages available.
Do I need to install [ngx-tour](https://www.npmjs.com/package/ngx-tour) or [ngx-tour-core](https://www.npmjs.com/package/ngx-tour-core) ?

I see that ngx-tour hasn't been updated since long whereas ngx-tour-core has been recently updated.

**Comment by isaacplmann** [comment]
There are 4 different ui options for ngx-tour.  [This page](https://isaacplmann.github.io/ngx-tour/) has a demo for each and the different install instructions for each one.

**Comment by isaacplmann** [comment]
Each of the ui plugins has a dependency on ngx-tour-core (so you don't have to explicitly install it).  ngx-tour doesn't actually do anything.  It's just a placeholder to stop typo squatting.

**Comment by pranavjain** [comment]
Thanks for the clarification.
