### ISSUE TITLE
TourByName and CurrentStep

### ISSUE THREAD

**Issue by pranavjain** [isaacplmann/ngx-tour#129]
Is there any way to add multiple tour and fetch them by name? Earlier implementation of library had that feature.
Also, how can I fetch the current step number? Earlier it used to be getCurrentStep() function.

**Comment by isaacplmann** [comment]
1. Resetting the tour steps to a new tour can be accomplished by calling

```ts
this.tourService.initialize(differentSteps);
```

You can set up your own service that takes care of switching between different sets of steps.

2. You can see the current step like this `this.tourService.currentStep`.

**Comment by pranavjain** [comment]
Thanks!
Is there a way to disable click outside the tour (which ends the tour) when backdrop is enabled?

**Comment by isaacplmann** [comment]
Nope.

You'd have to edit the library code and add `[hasBackdrop]="false"` on this line: https://github.com/isaacplmann/ngx-tour/blob/master/projects/ngx-tour-md-menu/src/lib/tour-step-template.component.ts#L16

**Comment by chriszrc** [comment]
I think it would be nice if the tourService.end$ returned the last `currentStep` (rather than nothing), that way it would be easier to tell which tour had just ended
