### ISSUE TITLE
Tour doesn't recognize HtmlElement with tourAnchor

### ISSUE THREAD

**Issue by Pieter-1337** [isaacplmann/ngx-tour#133]
Hi so I am making a tour and most part of it already works, however when I try to add a tourAnchor to a dynamically generated element(Material element, I add the touranchor when the element is generated), I  faced the issue that the tour initializes all elements up front. So I decided to split my tour in half and create a "new" tour which would then initialize after I added the tourAnchor to the dynamically generated material element.
However even in doing so it still says the element is not registered. Some help would be appreciated as I am really stuck on this one.

**Comment by isaacplmann** [comment]
How is the element created?

**Comment by Pieter-1337** [comment]
It gets created by Angular Material the element is the first topic addressed on the following page [https://material.angular.io/components/dialog/overview](url). The tour anchor I add dynammically through setAttribute(value, value) get's added to the element and after that I Initialize the tour so the tour should be able to find it as the element exists and has a tourAnchor. However it throws following error in console: Can't attach to unregistered anchor with id "MyTourAnchor", all other parts of the tour work so I'm assuming it's something on the tour's side?

**Comment by isaacplmann** [comment]
The problem is that Angular attaches directives only when they are pre-defined in the template.  Using `setAttribute` will add the html attribute, but won't attach the directive that is references by that attribute.

Material dialogs let you define the template yourself, so you should be able to add the `tourAnchor` in the template.

Or you could wait for the Ivy compiler to come out in about 6 months and then you'll be able to dynamically attach directives.

There are a few other options for work arounds if you want to share more of your code.

**Comment by Pieter-1337** [comment]
I managed to fix the problem by wrapping a div around my HTML code (and adding the tourAnchor there) which would be inserted dynamically in the element which is being generated and then reinitializing the tour and then getting the "new" tour to search for the directives after the Material element has been generated (so the element is visible from the dom). I'm afraid I can't share alot of code as this is for a real project.

**Comment by Urvisha-Parmar** [comment]
I am setting a directive value in similar way - setAttribute(value, value) and it does not work as touranchor is rendered in html instead of tourAnchor. Is there any way to fix it? 

Please note that I have to set directive and its value dynamically.

**Comment by Urvisha-Parmar** [comment]
I am setting a directive value in similar way - setAttribute(value, value) and it does not work as touranchor is rendered in html instead of tourAnchor. Is there any way to fix it?

Please note that I have to set directive and its value dynamically.
