### ISSUE TITLE
Is there any internet explorer support

### ISSUE THREAD

**Issue by Pieter-1337** [isaacplmann/ngx-tour#134]
Well has you can guess by the title..., I was surprised to find out that the tour doesn't really work well at all in internet explorer. Is there support for IE or do you guys just ignore it all together?

**Comment by isaacplmann** [comment]
Which UI plugin do you use?

**Comment by Pieter-1337** [comment]
I'm using Material right now, but if you try  to go to the ngx-tour-demo page [https://isaacplmann.github.io/ngx-tour/](url) it isn't even opening at all. The results I am getting when testing on IE are also pretty bad.

**Comment by isaacplmann** [comment]
Do you have the polyfills enabled for IE11?

**Comment by isaacplmann** [comment]
https://angular.io/guide/browser-support

**Comment by Pieter-1337** [comment]
Any specific polyfills you would recommend for working with the tour?

**Comment by isaacplmann** [comment]
Uncomment these in your polyfills.ts file:

```
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
// import 'core-js/es6/symbol';
// import 'core-js/es6/object';
// import 'core-js/es6/function';
// import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/string';
// import 'core-js/es6/date';
// import 'core-js/es6/array';
// import 'core-js/es6/regexp';
// import 'core-js/es6/map';
// import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```

**Comment by Pieter-1337** [comment]
Ok thx :)
