### ISSUE TITLE
Disable scroll upon active tour

### ISSUE THREAD

**Issue by shitanshusharma** [isaacplmann/ngx-tour#138]
This is not an issue exactly. 
But I need help in disabling the scroll while the tour is active. And reset it when the tour ends.

**Comment by shitanshusharma** [comment]
Found a workaround. Hence, closed it.

**Comment by Matiullah-karimi** [comment]
I have the same problem, could you please help me. @shitanshusharma

**Comment by isaacplmann** [comment]
You can subscribe to the `start$` and `end$` observables and do whatever logic you want.

**Comment by shitanshusharma** [comment]
Hi @Matiullah-karimi! As @isaacplmann suggested you can subscribe to `start$` observable and use
```
this.tourService.start$.subscribe(data => {
            $("html").css('margin','0');
            $("html").css('height','100%');
            $("html").css('overflow','hidden');
});
```

To reset it back to normal use it **End** button click or subscribe to `end$` observable:
```
reset() {
        $("html").css('margin','0');
        $("html").css('height','100%');
        $("html").css('overflow','auto');
}
```
