### ISSUE TITLE
Uncaught Error: Template parse errors: tour-step-template' is not a known element 

### ISSUE THREAD

**Issue by Kailiangdong** [isaacplmann/ngx-tour#143]
Excuse me. I'd like to integrate the ngx-tour to a simple angular app. 
I follow the usage in documentation/demo page. 
The compile is successful but the page can't be show in brower. It said" Uncaught Error: Template parse errors: tour-step-template' is not a known element ".
I thought it is some problem about <tour-step-template></tour-step-template>.

Can anyone help me ? Thank you in advanced

**Comment by isaacplmann** [comment]
That error happens when you have not imported the Tour Module in the same
module as the component that is using tour-step-template

**Comment by Kailiangdong** [comment]
@isaacplmann Thank you for your reply. The page can correctly show but the tour only show at the bottom. I think it is because I put <tour-step-template></tour-step-template> at the bottom in app.component.html. Because I want to test the ngx-tour on a simple app. So I didn't use Router. Is it somethings because of <router-outlet></router-outlet>?  Thank you for some suggestion.
![image](https://user-images.githubusercontent.com/38508002/48518636-89bf6780-e86a-11e8-9afd-b156a7a52bb2.png)
![image](https://user-images.githubusercontent.com/38508002/48518661-9774ed00-e86a-11e8-9ab0-07d72a214142.png)

**Comment by Kailiangdong** [comment]
![image](https://user-images.githubusercontent.com/38508002/48519657-fbe57b80-e86d-11e8-9270-36e070bf6a85.png)
![image](https://user-images.githubusercontent.com/38508002/48519738-37804580-e86e-11e8-88bc-930997671560.png)

**Comment by Kailiangdong** [comment]
It solved Thank you. @isaacplmann
