### ISSUE TITLE
npm install -> npm start: error

### ISSUE THREAD

**Issue by bsoulier** [isaacplmann/ngx-tour#144]
I have been trying mutliple times to build the project locally, but I always get errors.

Using https://github.com/isaacplmann/ngx-tour/issues/43 as a help did not work either.

npm run build:lib:all -> `projects/ngx-tour-console/src/lib/tour-anchor.directive.ts(1,63): error TS2307: Cannot find module 'ngx-tour-core'.`

npm start -> `The system cannot find the path specified.`

**Comment by isaacplmann** [comment]
I just tried this again after deleting the dist folder and node_modules.  I can't get the error you're experiencing.

I did:
1. Delete dist and node_modules
2. npm i
3. npm run build:lib:all
4. npm start

**Comment by bsoulier** [comment]
Still having the same issue.

Seems to be a platform related issue, I am running this on Windows 10.

**Comment by bsoulier** [comment]
I have been able to run it on a mac without a pb, so really seems to be a path issue

**Comment by isaacplmann** [comment]
Weird.  Let me know if you figure it out

**Comment by hakimio** [comment]
@bsoulier Can you test ["angular-7" branch on my fork](https://github.com/hakimio/ngx-tour/tree/angular-7). Does it build for you on Windows?
