### ISSUE TITLE
break line content

### ISSUE THREAD

**Issue by thari119** [isaacplmann/ngx-tour#148]
Hey guys. Anyone knows if its possible to break line using `<br />` or something so the content will go to next line instead of all been in one line?

**Comment by isaacplmann** [comment]
Unfortunately, it's kind awkward to do that right now.  You'll have to use the workaround described in #72 .

**Comment by sven513** [comment]
What's wrong with

```
<mat-card-content [innerHTML]="step?.content">
</mat-card-content>
```

in ``<tour-step-template>``?

Works for me...
