### ISSUE TITLE
Installation dependencies

### ISSUE THREAD

**Issue by Jswill64** [isaacplmann/ngx-tour#151]
Hello,

I tried installing NGX-Tour.
It looks like Angular 7 is required?
Is there a possibility to use it with Angular 6?

> `npm WARN ngx-tour-core@4.0.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN ngx-tour-core@4.0.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN ngx-tour-core@4.0.1 requires a peer of @angular/router@^7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @angular/cdk@7.1.1 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @angular/cdk@7.1.1 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @angular/material@7.1.1 requires a peer of @angular/animations@>=7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @angular/material@7.1.1 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @angular/material@7.1.1 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN ngx-tour-md-menu@4.0.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN ngx-tour-md-menu@4.0.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN ngx-tour-md-menu@4.0.1 requires a peer of @angular/animations@^7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 (node_modules/node-sass):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 postinstall: `node scripts/build.js`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> `

thanks in advance

**Comment by isaacplmann** [comment]
Use `ngx-tour-md-menu@3.1.1` to get rid of the warnings for Angular 6.  You might be able to get away with just running the latest version and ignoring the errors as well.

**Comment by gdmartinez93** [comment]
I have a similar problem, when I installed `ngx-tour-md-menu@3.1.1` I solved some issues but I have this problems:

`
ERROR in ./node_modules/ngx-tour-core/ngx-tour-core/ngx-tour-core.es5.js
Module not found: Error: Can't resolve 'rxjs/Subject' in '/home/gd.martinez/Downloads/Bakuq/Projects/good-job/webapp/node_modules/ngx-tour-core/ngx-tour-core'
ERROR in ./node_modules/ngx-tour-core/ngx-tour-core/ngx-tour-core.es5.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in '/home/gd.martinez/Downloads/Bakuq/Projects/good-job/webapp/node_modules/ngx-tour-core/ngx-tour-core'
ERROR in ./node_modules/ngx-tour-core/ngx-tour-core/ngx-tour-core.es5.js
Module not found: Error: Can't resolve 'rxjs/add/operator/first' in '/home/gd.martinez/Downloads/Bakuq/Projects/good-job/webapp/node_modules/ngx-tour-core/ngx-tour-core'
ERROR in ./node_modules/ngx-tour-core/ngx-tour-core/ngx-tour-core.es5.js
Module not found: Error: Can't resolve 'rxjs/operator/map' in '/home/gd.martinez/Downloads/Bakuq/Projects/good-job/webapp/node_modules/ngx-tour-core/ngx-tour-core'
ERROR in ./node_modules/ngx-tour-core/ngx-tour-core/ngx-tour-core.es5.js
Module not found: Error: Can't resolve 'rxjs/operator/merge' in '/home/gd.martinez/Downloads/Bakuq/Projects/good-job/webapp/node_modules/ngx-tour-core/ngx-tour-core'
`
Any idea about How solve this?
