### ISSUE TITLE
Clickable highlighted region and non-clickable backdrop.

### ISSUE THREAD

**Issue by aniket-02** [isaacplmann/ngx-tour#152]
How to make this happen?
using md-tour

**Comment by aniket-02** [comment]
Hi @hakimio ,
Thanks for your reply and quick help. Its says that we have to modify the library code. I am adding the library as a dependency in my angular app and using a custom template. Something like this...

`<ng-template #defaultTemplate let-step="step">
               ...
  </ng-template>`

How do we modify in the custom template?

**Comment by hakimio** [comment]
@aniket-02 you can't. You have to modify the line in the library indicated by Isaac in his comment.

**Comment by aniket-02** [comment]
@hakimio thanks for the help. 
@isaacplmann Are there any immediate plans of providing an endpoint / API for the toggling of the above feature?
