### ISSUE TITLE
 Tour Popper is not shown routing from one tab to the previous tab

### ISSUE THREAD

**Issue by ravirrk** [isaacplmann/ngx-tour#153]
Is there any way to show tour popper while I am routing from one tab to the previous tab. 
For Example:
I am showing a product tour on the toolbar which contains the following three tabs Home-> Gallery-> Login. So when I am routing from homepage to gallery page and so on a popper is shown suitably. But when I am going back from the login page to the gallery popper gets removed.

I want the current popper to be visible on the toolbar when I am routing from one page to previous pages.

**Comment by ravirrk** [comment]
Is there any way to show tour popper while I am routing from one tab to the previous tab. 
For Example:
I am showing a product tour on the toolbar which contains the following three tabs Home-> Gallery-> Login. So when I am routing from homepage to gallery page and so on a popper is shown suitably. But when I am going back from the login page to the gallery popper gets removed.

**Comment by isaacplmann** [comment]
PR #146 seems related to your issue.  If no `route` property is set on the current step, then navigating to a new route will not close the tour.

One option is to remove the `route` property from all the steps and manually subscribe to `stepHide$` or `stepShow$` observables and trigger your own routing changes there.
