### ISSUE TITLE
Tour Status shows '0' but tour continues.

### ISSUE THREAD

**Issue by aniket-02** [isaacplmann/ngx-tour#155]
Hi, @isaacplmann @hakimio 
While on tour running phase, at one stage the tourService.getStatus() returns 0 but the tour continues.

```ts
    this.menuCloseSubscription = this.opener.trigger.menuClosed
            .pipe(first())
            .subscribe(function () {
            if (_this.tourService.getStatus() !== TourState.OFF) {
                _this.tourService.end();
            }
            _this.tourBackdrop.close();
        });
    };
```

The above code is triggered. Could you please help out why is this happening. I am using the getStatus() function to do something if the tour is in running state.

**Comment by isaacplmann** [comment]
Which `ngx-tour` ui are you using?  And what version?

**Comment by aniket-02** [comment]
@isaacplmann i am using md-menu

**Comment by aniket-02** [comment]
"ngx-tour-core": "3.0.0",
"ngx-tour-md-menu": "3.1.1"

(We are using Angular 6)

**Comment by isaacplmann** [comment]
I think there's a bug here.  Calling `this.tourService.end()` should close the tour in the GUI, but it doesn't.

I'll work on fixing it, but I'll fix it in the latest version, not the 3.x version.

**Comment by isaacplmann** [comment]
It looks like there's a race condition happening somewhere.  Can you show me your code that is causing this to happen?

I was able to make `tourService.end()` close the GUI if I wrap it in a `setTimeout`.

```
setTimeout(() => {
  this.tourService.end();
});
```

**Comment by aniket-02** [comment]
@isaacplmann Thanks for the reply, my use case goes like this. I have an observable subscribed in my ngOnInit() and when the subscribe is called, I am making a tourService.next() call.

`
this.something.subscribe(v => {
        this.selected = v;
        switch (v) {
          case '1': this.stepIndex = 0; break;
          case '2': this.stepIndex = 1; break;
          case '3': this.stepIndex = 2; break;
          case '4': this.stepIndex = 3; break;
        }
        this.tourService.next();
` 
On clicking of the next button, the observable "something" is set which is subscribed in the above code. After the tourService.next() is called, the tour continues with next step, but the tourService.getStatus() returns 0
