### ISSUE TITLE
Service not starting the tour, no current step

### ISSUE THREAD

**Issue by d9nny** [isaacplmann/ngx-tour#156]
Hi, 

I'm unable to get the tour to start.

When I copy the service, I can see that the steps and anchors have been registered, but after `tourService.start()` nothing happens and if I `tourService.next()` then I get `Can't get next step. No currentStep`. Also, there is another module between AppModule and ModelsModule, in case that makes a difference.

app.module.ts
```
import { TourNgBootstrapModule, TourService } from 'ngx-tour-ng-bootstrap'

@NgModule({
    imports: [
        RouterModule.forRoot([]),
        TourNgBootstrapModule.forRoot(),
    ],
    providers: [
        TourService
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

app.component.ts
```
@Component({
    selector: 'cds-root',
    template: `<tour-step-template></tour-step-template>
                       <router-outlet></router-outlet>`
})
export class AppComponent implements OnInit {...}
```

models.module.ts - a lazy loaded module
```
import { TourNgBootstrapModule  } from 'ngx-tour-ng-bootstrap';

Module({
    imports: [
        TourNgBootstrapModule,
        RouterModule.forChild(routes)
    ],
    declarations: [
        ModelsLayoutComponent,
    ]
})
export class ModelsModule { }
```

models-layout.component.ts
```
import { TourService } from 'ngx-tour-ng-bootstrap';

export class ModelsLayoutComponent {
        
        constructor(private tourService: TourService) {}
        
        startTour() {
		console.log(this.tourService);
		this.tourService.initialize([
			{
				anchorId: 'start.tour',
				content: 'Welcome to this tour!',
				title: 'Welcome',
				route: '/forecast'
			},
			{
				anchorId: 'design.tour',
				content: 'Design description ....',
				title: 'Design',
				route: '/forecast'
			},
		]);
		this.tourService.start();
	}
}
```

models-layout.compoennt.html
```
<a class="btn btn-primary light-text btn-sm"
     (click)="startTour()">Start</a>

<div tourAnchor="start.tour"></div>

<div tourAnchor="design.tour"></div>
```

Thanks

**Comment by isaacplmann** [comment]
Try deleting these lines from your `AppModule`:

```ts
    providers: [
        TourService
    ],
```

I think that is providing a second `TourService` that is local to your app but is not the same as the one used internally by `NgxTourNgBootstrap`

**Comment by d9nny** [comment]
Thanks, unfortunately it hasn't changed anything.
Here is a screen shot of the service, as you can see it seems to have registered the anchors and steps, but when I start it doesn't seem to set `currrentStep`.

![screen shot 2019-01-07 at 17 07 32](https://user-images.githubusercontent.com/14181629/50782055-cf167900-129e-11e9-8c03-131455cf510f.png)

Any other ideas?

**Comment by isaacplmann** [comment]
Can you check if `<ngb-popover-window>` is added at the end of the body element in your Elements tab in developer tools?  If you don't have the bootstrap css loaded correctly, the tour won't show up visually (even if it is present in the DOM).

![image](https://user-images.githubusercontent.com/861504/50783217-2d7c3100-1278-11e9-8665-a2f29718b298.png)

**Comment by isaacplmann** [comment]
Also, what version of `ng-bootstrap` are you using?

**Comment by d9nny** [comment]
No it's hasn't been added.

Versions:
`@ng-bootstrap/ng-bootstrap": "^4.0.0`
`"bootstrap": "^4.0.0",`

angular.json
```
"architect": {
        "build": {
            ...,
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles/styles.less"
            ],
```

models.module.ts
```
@NgModule({
    imports: [
        ...,
        NgbModalModule, NgbTooltipModule, NgbPopoverModule,
        TourNgBootstrapModule,
        RouterModule.forChild(routes)
    ],
    declarations: [
        ModelsLayoutComponent,
    ]
})
export class ModelsModule { }

**Comment by d9nny** [comment]
I found the issue, my url has query parameters at the end, which I didn't include in the `route` property i.e. `/design` => `/design?modelid=32`. So at the below step, `navigated` was returning `false`.
Is there a way/ format, where it will ignore query params?

tour.service
```
goToStep(step) {
        console.log(step);
        if (!step) {
            console.warn('Can\'t go to non-existent step');
            this.end();
            return;
        }
        /** @type {?} */
        let navigatePromise = new Promise(resolve => resolve(true));
        if (step.route !== undefined && typeof step.route === 'string') {
            navigatePromise = this.router.navigateByUrl(step.route);
        }
        else if (step.route && Array.isArray(step.route)) {
            navigatePromise = this.router.navigate(step.route);
        }
        navigatePromise.then(navigated => {
            console.log(navigated)
            if (navigated !== false) {
                console.log('inside')
                setTimeout(() => this.setCurrentStep(step));
            }
        });
    }
```

**Comment by isaacplmann** [comment]
No, there isn’t a way to do that.  I really want to decouple the Router from the TourService so that people could inject their own implementation or not use the router at all.  I’m not sure when I’ll find time to do that though.
