### ISSUE TITLE
Problems starting the tour

### ISSUE THREAD

**Issue by gdmartinezsandino** [isaacplmann/ngx-tour#157]
Hello,

I have some issues when I try to start the tour, debugging the problem I have this output when is initialized

![image](https://user-images.githubusercontent.com/11862824/51279867-396c9f00-19ac-11e9-9cd9-119569f58343.png)

I have all the information declared on the component, but when the step is "Start"

![image](https://user-images.githubusercontent.com/11862824/51279902-5012f600-19ac-11e9-95bc-397e7d8c0cbf.png)

The values are lost, so, for this reason, the module returns me this answer:

![image](https://user-images.githubusercontent.com/11862824/51279929-67ea7a00-19ac-11e9-9cc2-15d024751748.png)

So, I don't have any idea why this not working, I verify the declarations and I have only one declaration to TourMatMenuModule.forRoot().

Any idea to solve this?

**Comment by themaawaa** [comment]
You only have to import the `TourMatMenuModule.forRoot().` in the **root** module. Any other module that is used, you need to import the tour service like this:

`import {Tour} from './tour';`

**Comment by gdmartinez93** [comment]
I read that post and followed the instructions, look at this:

![image](https://user-images.githubusercontent.com/11862824/51409579-3dc1c500-1b30-11e9-8e14-34c146938e24.png)

This is the declaration in the AppModule with the method forRoot().

![image](https://user-images.githubusercontent.com/11862824/51409618-66e25580-1b30-11e9-9d4e-c48a6c086205.png)

And this is the declaration in the module where I will use the Tour, you can see I only declarated the module TourMatMenuModule withuot the method .forRoot(). That's the suggestion by @isaacplmann in that post.

So... Any idea?

**Comment by gdmartinez93** [comment]
Sorry, I forget to share you that part:

![image](https://user-images.githubusercontent.com/11862824/51421309-7a121700-1b6a-11e9-9424-6c7cfb82bb5a.png)
this is the declaration in the constructor of the component where I using the tour.

![image](https://user-images.githubusercontent.com/11862824/51421320-944bf500-1b6a-11e9-8acb-ad5ef94c73ba.png)
this how I use the service to initialize the tour.
![image](https://user-images.githubusercontent.com/11862824/51421337-c3626680-1b6a-11e9-95e6-5e4095366e8c.png)
and this is the HTML element with one anchorId used in the initialization of the tour

**Comment by ainur122** [comment]
You may have imported the wrong service. Check the paths.
Correct:
import {TourService} from "ngx-tour-md-menu";
Wrong:
import {TourService} from "ngx-tour-core";

**Comment by gdmartinez93** [comment]
In fact, nop, that is the suggestion by the library.

Guys for any reason, my problem is not from the library. I manage roles for the users in the platform, I don't why with some users the tour works and with other users, the tour isn't working. So, definitely, the reason is different to an issue from the library. I'm working in that to tell you what is error and how to fix that.

**Comment by swapnildubey-7** [comment]
Is there any update on this issue?

**Comment by vijayshinde1705** [comment]
I also have the same problem so any solution related to the issue
