### ISSUE TITLE
Overriding backdrop color

### ISSUE THREAD

**Issue by maarten-wachters** [isaacplmann/ngx-tour#158]
Hello, I've been searching but I cannot seem to find how I can override the backdrop color.

I have tried the following and more:
1. Overriding the `.touranchor--is-active` background and boxshadow
2. Overriding the `cdk-container-overlay` and `cdk-overlay-backdrop` colors
3. Overriding the `ngx-tour_backdrop` class applied to the backdrop div.

**Comment by dws-tushargupta** [comment]
Hi themaawaa,
Instead of . `cdk-container-overlay` and `cdk-overlay-backdrop`, Give this a try
```.cdk-overlay-transparent-backdrop {
  background: rgb(146, 5, 5);  // desired color
}
```
