### ISSUE TITLE
Add tourAnchor to a hamburger Menu dynamically. 

### ISSUE THREAD

**Issue by smemane** [isaacplmann/ngx-tour#159]
I have a hamburger menu, which I open programmatically, as I go through the tourservice steps. Once opened, I am trying to highlight the menu items in the Hamburger menu. I tried using the code the author mentioned in one of the other issues - 

```
    <a mat-list-item *ngFor="let item of items"
       [routerLink]="item.route" routerLinkActive="active" routerLinkActiveOptions="{exact: true}">
<ng-template #materialIcon *ngIf="!!item.tourAnchor" tourAnchor="expand">
    </a>
```
with not much luck. TourService gets stuck at this point (after the hamburger menu is opened and when  I try to step the tour through the menu items) .

I see the anchor being registered -
`{name: "anchorRegister", value: "expand"}`

But, when the step is invoked, it throws an error -

```
core.js:1601 ERROR Error: First argument must be an element
at withinviewport (withinviewport.js:52)
at TourAnchorMatMenuDirective.push../node_modules/ngx-tour-md-menu/fesm5/ngx-tour-md-menu.js.TourAnchorMatMenuDirective.showTourStep (ngx-tour-md-menu.js:190)
```

I see the elem.nodeType is 8 (Comment - https://developer.mozilla.org/en-US/docs/Web/API/Comment)

What I get in auto generated HTML is - `<!--bindings={ "ng-reflect-tour-anchor": "expand" }-->`

I am relatively new to Angular (using angular 2), and a little confused, if the anchor is registered, why can I not find it as 'tourAnchor='expand'' in HTML and why is TourService not triggering the step (showing a dialog) ?

**Comment by smemane** [comment]
Just thought of sharing, I was able to get past this by wrapping the ng-template in a div, not completely there yet, as the menu item isn't highlighted as it should be, but gets the tour working

**Comment by themaawaa** [comment]
How I worked around a restriction like this in my application is on that step reinitialise the tour (with the anchor registered!) and start the tour at that step. This 'breaks' the flow programmatically, but shouldn't display this visually to the user
