### ISSUE TITLE
How to turn on enableBackdrop effect in ngx-tour v2.0.0. M using Angular5 and ngx-tour2.0.0?

### ISSUE THREAD

**Issue by dws-tushargupta** [isaacplmann/ngx-tour#160]

**Comment by dws-tushargupta** [comment]
Please tell me how to enable backdrop option in v2.0.0 as enableBackdrop: true gives error.

**Comment by isaacplmann** [comment]
That feature was probably not implemented in that version.

**Comment by dws-tushargupta** [comment]
Thanks for the response.
Is there any way(any css),that might help in achieving that effect?

**Comment by dws-tushargupta** [comment]
Successfully implemented backdrop effect by implementing following code in my global 'styles.scss'.

`.touranchor--is-active {
  position: relative;
  z-index: 1001	;
}

.cdk-overlay-transparent-backdrop {
  background: black;
}`
