### ISSUE TITLE
template has lower z-index

### ISSUE THREAD

**Issue by sfabriece** [isaacplmann/ngx-tour#161]
I'm trying to create a tour for a multi-page application with a custom template.

The first step is ok.
I can't click any buttons on the second step because the step has a lower z-index than the parent.

**Comment by isaacplmann** [comment]
Inspect the tour step popover and find out which element has the lower z-index and then write a global css rule to increase that z-index.

**Comment by sfabriece** [comment]
a suggestion @isaacplmann : 

In cases like above where you have given a sufficient answer, I would close the issue and let the discussion continue thereafter. That Might help to reduce the issue count IMO.

Thanks for the quick reply.
