### ISSUE TITLE
backdrop effect in ngx-bootstrap-tour

### ISSUE THREAD

**Issue by dws-tushargupta** [isaacplmann/ngx-tour#170]
How to enable backdrop effect in NgxBootstrap tour? M using Angular 5 .
Is there any support for it?

**Comment by hakimio** [comment]
No, there isn't.

**Comment by Ragurajan21** [comment]
is there any WorkAround?

**Comment by hakimio** [comment]
No.

**Comment by johnmakridis** [comment]
Hello,

Since backdrop effect is not yet supported in ngx-tour-ngx-bootstrap version, I tried to add the backdrop element manually after the tour start. It works fine, the backdrop is visible for all steps.

@hakimio @dws-tushargupta Guys, take a look at the following.

1. Manually create a backdrop element using Renderer2
2. Add the element on body
3. Subscribe for tour "End" button click in order to remove the backdrop element

`import { Injectable, Renderer2, RendererFactory2 } from '@angular/core';
import { TourService } from 'ngx-tour-ngx-bootstrap';


@Injectable({ providedIn: 'root' })

export class AppTourService {
    private renderer: Renderer2;
    private backdropElement;

    constructor(private rendererFactory: RendererFactory2, private tourService: TourService) {
        this.renderer = this.rendererFactory.createRenderer(null, null);
    }

    startAppTour(): void {

        this.tourService.initialize([
            {
                anchorId: 'tourAnchorNavbarAdd',
                content: 'Some content 1',
                title: 'First',
            },
            {
                anchorId: 'tourAnchor1',
                content: 'Some content',
                title: 'Second',
            },
            {
                anchorId: 'tourAnchor2',
                content: 'Other content',
                title: 'Third',
            }
        ]);


        this.tourService.end$.subscribe(() => { // on "End" button press, remove the backdrop
            if (this.backdropElement)
                this.renderer.removeChild(document.body, this.backdropElement);
        });


        // Start the Tour
        this.tourService.start();

        // Create the backdrop element
        this.backdropElement = this.renderer.createElement('bs-modal-backdrop');

        // Add bootstrap classes to the backdrop element
        this.renderer.addClass(this.backdropElement, 'modal-backdrop');
        this.renderer.addClass(this.backdropElement, 'fade');
        this.renderer.addClass(this.backdropElement, 'in');
        this.renderer.addClass(this.backdropElement, 'show');

        // Append the backdrop to the body
        this.renderer.appendChild(document.body, this.backdropElement);


    }

}
`

**Comment by talha-gurbuz** [comment]
> Hello,
> 
> Since backdrop effect is not yet supported in ngx-tour-ngx-bootstrap version, I tried to add the backdrop element manually after the tour start. It works fine, the backdrop is visible for all steps.
> 
> 1. Manually create a backdrop element using Renderer2
> 2. Add the element on body
> 3. Subscribe for tour "End" button click in order to remove the backdrop element
> 
> `import { Injectable, Renderer2, RendererFactory2 } from '@angular/core'; import { TourService } from 'ngx-tour-ngx-bootstrap';
> 
> @Injectable({ providedIn: 'root' })
> 
> export class AppTourService { private renderer: Renderer2; private backdropElement;
> 
> ```
> constructor(private rendererFactory: RendererFactory2, private tourService: TourService) {
>     this.renderer = this.rendererFactory.createRenderer(null, null);
> }
> 
> startAppTour(): void {
> 
>     this.tourService.initialize([
>         {
>             anchorId: 'tourAnchorNavbarAdd',
>             content: 'Some content 1',
>             title: 'First',
>         },
>         {
>             anchorId: 'tourAnchor1',
>             content: 'Some content',
>             title: 'Second',
>         },
>         {
>             anchorId: 'tourAnchor2',
>             content: 'Other content',
>             title: 'Third',
>         }
>     ]);
> 
> 
>     this.tourService.end$.subscribe(() => { // on "End" button press, remove the backdrop
>         if (this.backdropElement)
>             this.renderer.removeChild(document.body, this.backdropElement);
>     });
> 
> 
>     // Start the Tour
>     this.tourService.start();
> 
>     // Create the backdrop element
>     this.backdropElement = this.renderer.createElement('bs-modal-backdrop');
> 
>     // Add bootstrap classes to the backdrop element
>     this.renderer.addClass(this.backdropElement, 'modal-backdrop');
>     this.renderer.addClass(this.backdropElement, 'fade');
>     this.renderer.addClass(this.backdropElement, 'in');
>     this.renderer.addClass(this.backdropElement, 'show');
> 
>     // Append the backdrop to the body
>     this.renderer.appendChild(document.body, this.backdropElement);
> 
> 
> }
> ```
> 
> } `

Thanks for information it is working.

**Comment by hakimio** [comment]
Or you can just use ngx-ui-tour-ngx-bootstrap instead of this library to get built-in backdrop.
