### ISSUE TITLE
Tour service initialize 2nd instance

### ISSUE THREAD

**Issue by zehavibarak** [isaacplmann/ngx-tour#172]
Got 'Can't attach to unregistered anchor with id...'.
The anchors does register (I see it on debug), but the initialize() is called on a different instance!

**Comment by dgonzalez870** [comment]
If you are using `ngx-tour-md-menu`, then use this in your service or compoenet
`import { TourService } from 'ngx-tour-md-menu';` not `import { TourService } from 'ngx-tour-core';`

**Comment by arndt-s** [comment]
please document this - thats a nasty error

**Comment by alvaro-octal** [comment]
@dgonzalez870 you saved my day!

**Comment by Zaimbinjawaid** [comment]
Getting the same error but I'm using NGx-popper @dgonzalez870
