### ISSUE TITLE
Disable click outside a step

### ISSUE THREAD

**Issue by brieucdlf** [isaacplmann/ngx-tour#174]
Hey !

I would like to know if there is an easy way to block the click event when you click outside a step. I cannot figure it out without touching your module ...

I would like to contribute but can not compile your project... Can you give me the step to do it ? 

Thanks you very much for you time ! :)

**Comment by isaacplmann** [comment]
Which ui library are you using?

**Comment by brieucdlf** [comment]
Oh sorry, I am using the material library :)

**Comment by isaacplmann** [comment]
Try this in your `styles.scss` file:

```css
.cdk-overlay-backdrop {
  pointer-events: none;
}
```

**Comment by brieucdlf** [comment]
Hey !

Thanks for your answer, I managed to get it work with your solution.
I've disabled the scrolling as well with this solution in my app component:

```typescript
import { MAT_MENU_SCROLL_STRATEGY } from '@angular/material';
import { Overlay, BlockScrollStrategy } from '@angular/cdk/overlay';

export function scrollFactory(overlay: Overlay): () => BlockScrollStrategy {
  return () => overlay.scrollStrategies.block();
}
```

and in the decorator @Component:

```typescript
providers: [{ provide: MAT_MENU_SCROLL_STRATEGY, useFactory: scrollFactory, deps: [Overlay] }],
```

https://material.angular.io/components/menu/api
https://stackoverflow.com/questions/46888635/disable-scrolling-when-angular-material-select-is-open

Have a good day and thank you for your time !

**Comment by rviswak** [comment]
> Try this in your `styles.scss` file:
> 
> ```css
> .cdk-overlay-backdrop {
>   pointer-events: none;
> }
> ```

hi The above code disable click outside the matcard on pointer events. wen i hover a button the hand comes and wen i click a button the events happens. please let me know how to avoid it
