### ISSUE TITLE
ivy has problem with merging the input and query decorator

### ISSUE THREAD

**Issue by sheikalthaf** [isaacplmann/ngx-tour#186]
ivy failed to compile due to multiple decorators is placed in one property

https://github.com/isaacplmann/ngx-tour/blob/888080a6d62371d22e33177c445be233974f4bff/projects/ngx-tour-md-menu/src/lib/tour-step-template.component.ts#L44

**Comment by maarten-wachters** [comment]
Delete line 43 `Input()` on your template and it should work just fine

**Comment by isaacplmann** [comment]
Fixed in version 4.1.0.  Please re-open if this is still an issue.
