### ISSUE TITLE
Error on NPM Install for bootstrap

### ISSUE THREAD

**Issue by queejie** [isaacplmann/ngx-tour#2]
I'm very sure the problem isn't permission related, but I can't think what else might be happening.
Thanks for any help you might be able to offer.

```
Daves-Macbook:frontend dqj$ npm install --save ng2-tour
npm ERR! addLocal Could not install /Users/dqj/Local/dev/apps/pl3/nocti/frontend/node_modules/ng2-tour/ng-bootstrap-ng-bootstrap-1.0.0-alpha.15.tgz
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "install" "--save" "ng2-tour"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5
npm ERR! path /Users/dqj/Local/dev/apps/pl3/nocti/frontend/node_modules/ng2-tour/ng-bootstrap-ng-bootstrap-1.0.0-alpha.15.tgz
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/dqj/Local/dev/apps/pl3/nocti/frontend/node_modules/ng2-tour/ng-bootstrap-ng-bootstrap-1.0.0-alpha.15.tgz'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/dqj/Local/dev/apps/pl3/nocti/frontend/node_modules/ng2-tour/ng-bootstrap-ng-bootstrap-1.0.0-alpha.15.tgz'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dqj/Local/dev/apps/pl3/nocti/frontend/npm-debug.log
```

**Comment by isaacplmann** [comment]
Yes, I need to get back to this project.  Hopefully in the next week or so.

**Comment by queejie** [comment]
Thanks for getting back to me!  I was just updating my comment as I received your note.

**Comment by isaacplmann** [comment]
I'm relying on a locally built version of ng-bootstrap, which isn't in the repo.  The fix that I needed from ng-bootstrap is now in the published version of ng-bootstrap, so I can make this library work correctly for everyone now -- I just need to get around to it.

**Comment by isaacplmann** [comment]
If you want to try a PR, you could update the package.json to point to the latest @ng-bootstrap/ng-bootstrap and see if it works.

**Comment by queejie** [comment]
Thank you.  I'm still not adept enough with git, but I'll try it.  Please excuse me if I make mistakes while learning how to do a pull request, etc.

**Comment by isaacplmann** [comment]
No problem.  Let me know if you get stuck - I’ll try to help.

**Comment by readelobdill** [comment]
Hi there,

Installing the latest @ng-bootstrap/ng-bootstrap fixes the install error!

But I am running into another error. I am attempting to complete `2) import TourNgBootstrapModule into your app module` with: 
```import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { TourNgBootstrapModule } from 'ng2-tour/src/lib/plugin/ng-bootstrap/ng-bootstrap.module';

@NgModule({
  imports: [
    CommonModule,,
    TourNgBootstrapModule
  ]
})

export default class AppModule { }
``` 
 and am running into: `Error: Unexpected value 'TourNgBootstrapModule' imported by the module 'AppModule'`

Am I doing something wrong here? Would be grateful for any advice you can provide, cheers!

**Comment by isaacplmann** [comment]
Probably not doing anything wrong.  I think I left this library in a state
of disrepair.  I hope to fix it soon.

**Comment by isaacplmann** [comment]
I think its working now.  Let me know if version 0.1.3 works for you.
