### ISSUE TITLE
Import error for ngx-bootstrap 5.5.0+ (Cannot find module)

### ISSUE THREAD

**Issue by bartromgens** [isaacplmann/ngx-tour#202]
For ngx-bootstrap to 5.5.0 or higher, I get the following import error:

```
ERROR in node_modules/ngx-tour-ngx-bootstrap/lib/tour-anchor.directive.d.ts:2:34 - error TS2307: Cannot find module 'ngx-bootstrap'. 
import { PopoverDirective } from 'ngx-bootstrap';
```

The import should be changed to `import { PopoverDirective } from 'ngx-bootstrap/popover';`

ngx-bootstrap 5.6.0+ is required for Angular 9 because it fixes a build error (https://github.com/valor-software/ngx-bootstrap/pull/5658)

**Comment by hectorp55** [comment]
Any update on this? Is there a work around in the meantime?

**Comment by bartromgens** [comment]
@hectorp55 I don't know of any workaround.

@isaacplmann I submitted #203 to fix this. It is a small change that is needed for Angular 9.

**Comment by krtek4** [comment]
Any chance this could be merged and released soon ?

It's the only issue left that I have before migrating to Angular 9

**Comment by vincentjdc** [comment]
Any news about this ?
There is already a PR but not merged :-s
