### ISSUE TITLE
body max height conflict with sticky footer

### ISSUE THREAD

**Issue by gilhanan** [isaacplmann/ngx-tour#21]
recently i installed ng2-tour to my project but i counting on wierd behavior which my stick footer stucks in bottom of the view port.
after few research i saw weird style rule in this library code:

`styles: ['body { max-height: 100vh; }']`
> tour-step-template.component.ts

i made [plunker](https://plnkr.co/edit/j45mx1aUxpvDFjztc0sA?p=preview]) of [bootstrap-4-sticky-footer](http://v4-alpha.getbootstrap.com/examples/sticky-footer/) with `body { max-height: 100vh; }` and more content (for scrolling) to demonstrate the problem:
![image](https://cloud.githubusercontent.com/assets/5566282/26151810/1391db94-3b0d-11e7-84df-cf48cae4aecc.png)

**Comment by gilhanan** [comment]
Thanks for that information I will try to find proper sollution and update
the PR

**Comment by isaacplmann** [comment]
Fixed in `ngx-tour-ng-bootstrap@1.0.3`
