### ISSUE TITLE
How to not stop the tour on clicking outside - mdMenu

### ISSUE THREAD

**Issue by rviswak** [isaacplmann/ngx-tour#210]

**Comment by hiren3897** [comment]
I am looking for the same did you found any solution about it.
If yes please let me know about it

**Comment by Judp0m** [comment]
I am also looking for such a feature.

**Comment by bfredo123** [comment]
Me too. I would like to make a tutorial where user clicks on buttons, enter text in form fields, while being guided with ngx-tour. How to manage this? Many thanks in advance. Great package btw.
