### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by fergardi** [isaacplmann/ngx-tour#215]
Hello!

I was trying to update from Angular9 to Angular10 and got this error:

```
Using package manager: 'npm'
Collecting installed dependencies...
Found 57 dependencies.
Fetching dependency metadata from registry...
                  Package "ngx-tour-core" has an incompatible peer dependency to "@angular/core" (requires ">=7.0.0 <9.0.0" (extended), would install "10.0.0").
                  Package "ngx-tour-core" has an incompatible peer dependency to "@angular/common" (requires ">=7.0.0 <9.0.0" (extended), would install "10.0.0").
                  Package "ngx-tour-md-menu" has an incompatible peer dependency to "@angular/animations" (requires ">=7.0.0 <9.0.0" (extended), would install "10.0.0").
                  Package "ngx-tour-core" has an incompatible peer dependency to "@angular/router" (requires ">=7.0.0 <9.0.0" (extended), would install "10.0.0").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

Any plans to upgrade to Angular10?

**Comment by soarfalc** [comment]
I join the request

**Comment by fergardi** [comment]
Any news? Is this repository still maintained?

**Comment by fergardi** [comment]
Due to the lack of responses I finally managed to "solve" this issue with the `--force` flag. Everything is working as expected.

**Comment by hakimio** [comment]
@fergardi you should leave this open until Angular 10 support is officially added to the project.

**Comment by IgnacioHR** [comment]
+1

**Comment by abdulbadisabir** [comment]
+1

**Comment by spike008t** [comment]
+1

**Comment by spike008t** [comment]
@isaacplmann any idea when `4.2.0` will be published?

**Comment by fergardi** [comment]
We are on Angular11 already, and no news...

**Comment by alvaro-octal** [comment]
I forked this library re-published under another name, I've not completed the automation of publishing (i order to avoid this scenarios) but for anyone interested you can use `@ngx-tour/core`

https://www.npmjs.com/settings/ngx-tour/packages

**Comment by hakimio** [comment]
I have created [a fork](https://github.com/hakimio/ngx-ui-tour) and I have published a new version under a new name: `ngx-ui-tour`. It's compatible with Angular 11. Test it out and let me know if it works as intended.
