### ISSUE TITLE
Prevent popup from closing when you click outside or inside

### ISSUE THREAD

**Issue by dirttech** [isaacplmann/ngx-tour#216]
I am using ngx-tour-ng-bootstrap and it closes whenever click inside or outside the popover

**Comment by nikoes** [comment]
A quick hack for this would be adding 

`
::ng-deep .cdk-overlay-backdrop {
    pointer-events: none!important;
}
`

But this will override the default material behavior related to modals and dialogs and it is not a very good solution.

**Comment by ahmedeldeeb25** [comment]
I have the same problem and I hope to find a good solution. @isaacplmann

**Comment by ahmedeldeeb25** [comment]
I found a solution that may help you.
In your Angular App -> index.html, after </body> add this

<style>
        .cdk-overlay-container {
                position: unset;
                z-index: 0;
        }

        .cdk-overlay-backdrop {
                position: unset;
                z-index: 0;
        }
</style>

You may need to adjust z-index style depend on your case.
