### ISSUE TITLE
Adding maintainers

### ISSUE THREAD

**Issue by hungerregnuh** [isaacplmann/ngx-tour#218]
Hey @isaacplmann ,

We've been using this package with our projects and need to update a few things, would you be willing to add us as maintainers?

**Comment by isaacplmann** [comment]
@hakimio, would you like to have rights merge in PRs?

**Comment by hakimio** [comment]
@isaacplmann yes, I could try to help you maintain this library.

**Comment by hakimio** [comment]
@isaacplmann can you publish a new version of the lib?

**Comment by hakimio** [comment]
@isaacplmann do you want me to publish new versions as well?

**Comment by hakimio** [comment]
@isaacplmann Still alive?

**Comment by hakimio** [comment]
@isaacplmann Should I just archive this repository and create a new one since you forgot to give permissions for publishing new versions to npm?
