### ISSUE TITLE
After update angular 10 I have got a compilation errors. 

### ISSUE THREAD

**Issue by harleenarora** [isaacplmann/ngx-tour#219]
Error::
`Error: Failed to compile entry-point ngx-tour-ng-bootstrap (es2015 as esm2015) due to compilation errors:
node_modules/ngx-tour-ng-bootstrap/fesm2015/ngx-tour-ng-bootstrap.js:248:26 - error NG1010: Value at position 1 in the NgModule.imports of TourNgBootstrapModule is not a reference: [object Object]

248                 imports: [CommonModule, NgbPopoverModule.forRoot()],`

Please solved this issue.

**Comment by fergardi** [comment]
Duplicate from #215

**Comment by abdulbadisabir** [comment]
I have the exact same error, any news?

**Comment by alvaro-octal** [comment]
This is now fixed, but we need a release @isaacplmann

**Comment by notman** [comment]
Any chance this release will be soon? We are at a stopping point, in our current upgrade to Angular 11

**Comment by hakimio** [comment]
@notman 
Bad news: Isaac Mann stopped maintaining this project some time ago and I don't have access to publish new npm packages.
Good news: I have created [a fork](https://github.com/hakimio/ngx-ui-tour) and I have published a new version under a new name: `ngx-ui-tour`. It's compatible with Angular 11. Test it out and let me know if it works as intended.
