### ISSUE TITLE
show each step after that contents completely render 

### ISSUE THREAD

**Issue by amirmostaghim** [isaacplmann/ngx-tour#223]
I have multi steps in different route and after navigate to one route, because of that the content of 'tourAchor' directive not completely render on that route, its step not showing properly on the page

**Comment by NMSaiyed** [comment]
On your router event changes register the tourAnchors as per the page requirement.
Then start the tour service from the tourAnchor of that page on initialisation.
But, you have set timeout and wait until your all html page elements rendered. Then ngx-tour will create the steps for you. It will take maximum 1s i believe so keep 1000 ms for timeout (test and keep timeout as per your need)

**Comment by jyz16** [comment]
I also came across this issue - @NMSaiyed could you elaborate on what you meant by start the tour service from the tourAnchor of that page on initialisation? Should I pass the tour service from `app.component.ts` to my child component, so I can call `pause()` and `start()` there?

**Comment by tarangkhandelwal** [comment]
How do we wait between the steps if the HTML elements are taking time to render and there is route change involved?
