### ISSUE TITLE
popover element added additional between routes

### ISSUE THREAD

**Issue by gilhanan** [isaacplmann/ngx-tour#23]
current behavior happens in [demo](https://isaacplmann.github.io/ng2-tour/) page so i didn't make plunker but after stepping the tour to next route, while developer tools is open, this is the image i got:
![image](https://cloud.githubusercontent.com/assets/5566282/26199483/d19ea412-3bd2-11e7-8ff0-cc596d024c26.png)

**Comment by isaacplmann** [comment]
Thanks for the bug report.  I'll take a look.

**Comment by isaacplmann** [comment]
Fixed in `ngx-tour-ng-bootstrap@1.x` and `ngx-tour-md-menu@1.x`

**Comment by gilhanan** [comment]
Awesome thanks
