### ISSUE TITLE
Relase ngx-tour-ngx-bootstrap

### ISSUE THREAD

**Issue by benj0c** [isaacplmann/ngx-tour#236]
@isaacplmann when do you plan to release 4.3.0 version of `ngx-tour-ngx-bootstrap` package on npm?

After update angular on version 10, and `ngx-bootstrap` on version `6.1.0` some problem occurs. 
I have already created an issue #235 for that. So I think maybe new version will helps to resolve this.

Not sure, but this https://github.com/isaacplmann/ngx-tour/commit/5d1a2e285919800ea70bf690838a0b1ff299266d commit seems as fix for that.

**Comment by mrsarm** [comment]
Having the same issue, ngx-tour-ngx-bootstrap is not compatible with the last version of Angular, so this is a mayor issue.
