### ISSUE TITLE
ERROR in node_modules/ngx-tour-core/lib/tour.service.d.ts(2,13): error TS1005: '=' expected.

### ISSUE THREAD

**Issue by shannon1720** [isaacplmann/ngx-tour#238]
ERROR in node_modules/ngx-tour-core/lib/tour.service.d.ts(2,13): error TS1005: '=' expected.
node_modules/ngx-tour-core/lib/tour.service.d.ts(2,33): error TS1005: ';' expected.
node_modules/ngx-tour-md-menu/lib/tour-anchor.directive.d.ts(2,13): error TS1005: '=' expected.
node_modules/ngx-tour-md-menu/lib/tour-anchor.directive.d.ts(2,40): error TS1005: ';' expected.

i ｢wdm｣: Failed to compile.
    
    ERROR in node_modules/ngx-tour-core/lib/tour.service.d.ts(2,15): error TS2304: Cannot find name 'UrlSegment'.
    node_modules/ngx-tour-core/lib/tour.service.d.ts(2,28): error TS2304: Cannot find name 'from'.
    node_modules/ngx-tour-core/lib/tour.service.d.ts(10,22): error TS2304: Cannot find name 'UrlSegment'.
    node_modules/ngx-tour-md-menu/lib/tour-anchor.directive.d.ts(2,15): error TS2304: Cannot find name 'OnDestroy'.
    node_modules/ngx-tour-md-menu/lib/tour-anchor.directive.d.ts(2,15): error TS2695: Left side of comma operator is unused and has no side effects.
    node_modules/ngx-tour-md-menu/lib/tour-anchor.directive.d.ts(2,26): error TS2304: Cannot find name 'OnInit'.
    node_modules/ngx-tour-md-menu/lib/tour-anchor.directive.d.ts(2,35): error TS2304: Cannot find name 'from'.
    node_modules/ngx-tour-md-menu/lib/tour-anchor.directive.d.ts(10,60): error TS2304: Cannot find name 'OnInit'.
    node_modules/ngx-tour-md-menu/lib/tour-anchor.directive.d.ts(10,68): error TS2304: Cannot find name 'OnDestroy'.

**Comment by Ashish117** [comment]
@isaacplmann I am experience the same problem.

**Comment by Praveen-1998** [comment]
I am also getting same error

**Comment by hakimio** [comment]
What version of Angular and ngx-tour-core are you using?

**Comment by hakimio** [comment]
The reason for this error is because you are using TypeScript version lower than 3.8. Type imports where introduced in [TS 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html).
Not sure if we can do anything except raise TS version requirement.

**Comment by hakimio** [comment]
I have created [a fork](https://github.com/hakimio/ngx-ui-tour) of this project which now requires TypeScript >= 3.8 and Angular >= 9.
