### ISSUE TITLE
Repeated component: "ERROR Error: anchorId XXX already registered!"

### ISSUE THREAD

**Issue by alexJaegerSTR** [isaacplmann/ngx-tour#24]
When using *ngFor or manually including a component (with a defined tourAnchor attribute) multiple times an error is thrown and  the page breaks. 

Possible solution:
Allow to overwrite anchor bindings (if needed enabled with a configuration option)

**Comment by isaacplmann** [comment]
So you want the last `tourAnchor` of the same name to overwrite any previous ones?

You could probably get into some weird non-deterministic use cases with that feature.  i.e. the last `tourAnchor` would vary depending on the order components were rendered.

What's the motivation for this feature request?

**Comment by damo1884** [comment]
This would actually help with a responsive/adaptive UI also when the browser is resized and element get removed and re-added somewhere else I also get this error.

What is the best way to avoid this error from happening?

Do I have to unregister each anchor in each component when ngDestroy is called and add them back in again?

**Comment by isaacplmann** [comment]
The `tourAnchor` directive automatically unregisters itself in the `ngOnDestroy` method.  You'll only get this error if the `ngOnDestroy` method of the first anchor happens after the `ngOnInit` method of the second anchor (with the same `anchorId`).

@damo1884 making this change would be a breaking change.  Want to make a branch and work on this feature?
