### ISSUE TITLE
Enable HTML tags in step content

### ISSUE THREAD

**Issue by HEBOS** [isaacplmann/ngx-tour#240]
Hi,

I've added a [PR](https://github.com/isaacplmann/ngx-tour/pull/239) which enables users to add HTML to the step content.

Thank you

**Comment by hakimio** [comment]
@HEBOS 
Bad news: Isaac Mann stopped maintaining this project some time ago and I don't have access to publish new npm packages.
Good news: I have created [a fork](https://github.com/hakimio/ngx-ui-tour) which includes your PR and I have published a new version under a new name: `ngx-ui-tour`. Test it out and let me know if it works as intended.
