### ISSUE TITLE
enableBackdrop missing in IStepOption?

### ISSUE THREAD

**Issue by pstadler1990** [isaacplmann/ngx-tour#241]
The `IStepOption` interface seems to exclude the `enableBackdrop` property, however it seems that this property is an attribute of a single step, right? It's also listed on the [website](https://isaacplmann.github.io/ngx-tour/).

**Comment by hakimio** [comment]
It's only implemented for `ngx-tour-md-menu` -> https://github.com/isaacplmann/ngx-tour/blob/master/projects/ngx-tour-md-menu/src/lib/step-option.interface.ts#L4
