### ISSUE TITLE
Overlay doesn't go away on navigating back

### ISSUE THREAD

**Issue by HEBOS** [isaacplmann/ngx-tour#242]
Currently if a tour dialog is opened (step 1), and we go back (using browser or keyboard back), the overlay doesn't go away, but covers the previous page too.

It would be great to use what [Angular team has introduced](https://github.com/angular/components/pull/12592/commits/346d4550b496e2a517e238bbbd99e8e3f357ecdb)

**Comment by hakimio** [comment]
@HEBOS if you would open a new PR to address this issue in [hakimio/ngx-ui-tour](https://github.com/hakimio/ngx-ui-tour) I could review it for inclusion in there.
