### ISSUE TITLE
Skip a step when the anchorId is undefined

### ISSUE THREAD

**Issue by SamashaNayananthi** [isaacplmann/ngx-tour#253]
Hi,

I have noticed in the stepShow$ method when there isn't an anchor defined the process gets exit. Is that possible to skip a step to the next step when there isn't an anchor is defined?

Thanks

**Comment by hakimio** [comment]
First of all, as clearly stated in the [README](https://github.com/isaacplmann/ngx-tour#readme) this library is not maintained anymore and all feature requests and bug reports should be opened in [ngx-ui-tour](https://github.com/hakimio/ngx-ui-tour) repository.

Anyway, to answer your question: no, all steps should have valid anchor id. If you want some steps to be skipped, don't include them when initializing the tour. If the state of the app changes, you can reinitialize the tour whenever needed.

Similar old issues:
https://github.com/isaacplmann/ngx-tour/issues/70
https://github.com/isaacplmann/ngx-tour/issues/107

**Comment by hakimio** [comment]
@SamashaNayananthi I have added this feature to [the latest version of ngx-ui-tour](https://github.com/hakimio/ngx-ui-tour/releases/tag/v6.1.0) I maintain.
