### ISSUE TITLE
Sriram 

### ISSUE THREAD

**Issue by sriram-sayila** [isaacplmann/ngx-tour#278]
Getting error can't attach to unregistered anchor with start.tour. I used mdmenu. I checked previous commments and solutions  and tried all thing still same issue.

can you suggest a solution

**Comment by lukyncze** [comment]
@sriram-sayila This project is no longer being maintained. You can see it [here](https://github.com/isaacplmann/ngx-tour#notice-this-project-is-no-longer-being-maintained-warning).

Try using new replacement: [Ngx UI Tour](https://github.com/hakimio/ngx-ui-tour) :1st_place_medal:

**Comment by sriram-sayila** [comment]
Okay @lukyncze Thanks
