### ISSUE TITLE
Error: Can't resolve 'scroll-into-view-if-needed' 

### ISSUE THREAD

**Issue by di3orlive** [isaacplmann/ngx-tour#28]
get this err after install 
`npm install ng2-tour`
and 
`npm install angular2-hotkeys --save`

`ERROR in ./~/ng2-tour/src/lib/plugin/ng-bootstrap/tour-anchor.directive.js
Module not found: Error: Can't resolve 'scroll-into-view-if-needed' in 'D:\PROJECTS\O4P\node_modules\ng2-tour\src\lib\plugin\ng-bootstrap'
 @ ./~/ng2-tour/src/lib/plugin/ng-bootstrap/tour-anchor.directive.js 12:29-66 12:78-115
 @ ./~/ng2-tour/src/lib/plugin/ng-bootstrap/ng-bootstrap.module.js
 @ ./~/ng2-tour/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

    {
      "dependencies": {
        "@angular/animations": "^4.1.3",
        "@angular/cdk": "^2.0.0-beta.8",
        "@angular/common": "^4.0.0",
        "@angular/compiler": "^4.0.0",
        "@angular/core": "^4.0.0",
        "@angular/forms": "^4.0.0",
        "@angular/http": "^4.0.0",
        "@angular/material": "^2.0.0-beta.8",
        "@angular/platform-browser": "^4.0.0",
        "@angular/platform-browser-dynamic": "^4.0.0",
        "@angular/router": "^4.0.0",
        "@ngx-translate/core": "^7.0.0",
        "@ngx-translate/http-loader": "0.1.0",
        "@types/highcharts": "^4.2.57",
        "@types/socket.io-client": "^1.4.29",
        "angular2-hotkeys": "^2.0.1",
        "core-js": "^2.4.1",
        "hammerjs": "^2.0.8",
        "highcharts": "^5.0.12",
        "js-sha256": "^0.6.0",
        "md2": "0.0.25",
        "ng-inline-svg": "^3.2.1",
        "ng2-highcharts": "^1.0.0",
        "ng2-nouislider": "^1.6.1",
        "ng2-validation": "^4.2.0",
        "ngx-facebook": "^2.4.0",
        "ngx-infinite-scroll": "^0.5.1",
        "nouislider": "^10.0.0",
        "rxjs": "^5.1.0",
        "socket.io-client": "^2.0.3",
        "zone.js": "^0.8.4"
      }
    }

**Comment by di3orlive** [comment]
+ `npm i scroll-into-view-if-needed` and err disappear

**Comment by isaacplmann** [comment]
Fixed in `ngx-tour-ng-bootstrap@1.x` and `ngx-tour-md-menu@1.x`.  `scroll-into-view-if-needed` is no longer used.
