### ISSUE TITLE
Installing ng2-tour

### ISSUE THREAD

**Issue by assaflei** [isaacplmann/ngx-tour#31]
Hi,
I'm trying to install the package using the standard npm install ng2-tour
I noticed that the package.json file included in the installation has older peer dependencies than those that exist in the root directory package.json

This is what it requires when installing the package:
npm WARN ng2-tour@0.1.7 requires a peer of @angular/common@^2.4.5 but none was installed.
npm WARN ng2-tour@0.1.7 requires a peer of @angular/core@^2.4.5 but none was installed.
npm WARN ng2-tour@0.1.7 requires a peer of @angular/router@^3.4.5 but none was installed.
npm WARN ng2-tour@0.1.7 requires a peer of angular2-hotkeys@1.x.x but none was installed.
npm WARN ng2-tour@0.1.7 requires a peer of core-js@^2.4.1 but none was installed.
npm WARN ng2-tour@0.1.7 requires a peer of scroll-into-view-if-needed@^1.1.0 but none was installed.
npm WARN ng2-tour@0.1.7 requires a peer of zone.js@^0.7.6 but none was installed.

I edited the package.json file in my local node_modules\ng2-tour, and went off from there .

**Comment by isaacplmann** [comment]
I need to update the documentation for version 1.x.  You'll be installing ngx-tour-md-menu or ngx-tour-ng-bootstrap instead of ng2-tour.  More details to come.

**Comment by assaflei** [comment]
Until version is ready I should use ng2-tour? 
Or I should use the other packages already?

**Comment by isaacplmann** [comment]
Version 1.x should be working, but I haven't updated the documentation to go with it.

**Comment by isaacplmann** [comment]
I'm having a tough time fixing issue #30 and I don't think the library is very usable until that is fixed.  I'll try to get that fixed as soon as possible.

**Comment by isaacplmann** [comment]
Finally fixed that issue.  Check out the new [documentation](https://isaacplmann.github.io/ngx-tour/).
