### ISSUE TITLE
Module '"D:/www/AnnualReportWeb/node_modules/@angular/material/material"' has no exported member 'Directionality'.

### ISSUE THREAD

**Issue by jorawarsingh** [isaacplmann/ngx-tour#34]
Hi! great work 👍  demo works well online but tried in my project and getting some error. Your module is depeneden on Directionality from material but there is no such exported. i went through material and could not found it.

**Comment by isaacplmann** [comment]
Directionality is only in the `@angular/material@2.0.0-beta.8` and up.   You're probably on beta.7 or lower.

**Comment by jorawarsingh** [comment]
thanks this was the issue and now it works. I have some other issues, tour stats as accepts but say i have multiple components and i want it to jump to next component when it is done with the first but it ends there? is there any ongoing work on this or new feature request?

**Comment by isaacplmann** [comment]
I'm not sure what you're asking for.  Can you describe it step by step?  Screenshots help too.

**Comment by jorawarsingh** [comment]
![ngtour](https://user-images.githubusercontent.com/7203792/28993631-f8453fce-79d8-11e7-8915-4e0813287bfd.png)
Ok i will to explain it more. As you can see in picture i have commponent abc and tour start with a but it never goes to b it ends on a. What can it be?

**Comment by isaacplmann** [comment]
I'm on vacation until Wednesday. I will respond then.

**Comment by isaacplmann** [comment]
Do you have a `tourAnchor` directive on component B?  And does your tour step reference that anchor?

**Comment by jorawarsingh** [comment]
Yes i have it and tour step do reference to it.

My Scenario is like this

1. User login and come to dash board where user see first tour
2. User go to next view and then i want to start tour again from next point

but when it has been ended on first time it never show up again on next route. May be i missed something. I hope i could explain it to you otherwise i can try to make a sketch of what i am looking for.

**Comment by isaacplmann** [comment]
Can you show me your code?  How are you "ending" the first step?  And how do you "start" the next step?  What does your step configuration look like?
