### ISSUE TITLE
update ngx-tour-core dependency of zone.js to match that of ngx-tour

### ISSUE THREAD

**Issue by tcozzens** [isaacplmann/ngx-tour#35]
I was hoping that you could update ngx-tour-core dependency of zone.js to match that of ngx-tour, ^0.8.12.

This is causing package unmet dependencies on install of this package. 

I attempted to fork and do a PR, but I cant seem to get the change to work.. Keeps saying "npm WARN ngx-tour-core@1.0.2 requires a peer of zone.js@^0.7.6 but none was installed."

Then again, I am not the best with NPM and packaging. 

Thanks

**Comment by tcozzens** [comment]
I made a PR for this. However, not sure if it's 100% right. 

#37

**Comment by isaacplmann** [comment]
ngx-tour-core@1.0.3 is now published.  FYI, ngx-tour is the old (pre 1.x) version of the library.  You'll want to use ngx-tour-md-menu or ngx-tour-ng-bootstrap without directly install ngx-tour-core.

**Comment by tcozzens** [comment]
yes, I was using ngx-tour-ng-bootstrap.

**Comment by tcozzens** [comment]
This works for me now, I appreciate the help!
