### ISSUE TITLE
AOT

### ISSUE THREAD

**Issue by KingsDevelopment** [isaacplmann/ngx-tour#36]
I am getting the following error when using AOT:
`Error: No component factory found for NgbPopoverWindow. Did you add it to @NgModule.entryComponents?`

Any good ideas how I could solve this?

**Comment by isaacplmann** [comment]
Do you have @ng-bootstrap/ng-bootstrap included in your package.json?

**Comment by KingsDevelopment** [comment]
yes sir, on the latest alpha

**Comment by KingsDevelopment** [comment]
ps. also tried with alpa.27

**Comment by KingsDevelopment** [comment]
Any updates? @isaacplmann

**Comment by isaacplmann** [comment]
I'm on vacation until Wednesday. I'll respond then.

**Comment by isaacplmann** [comment]
I was using the [wrong configuration](https://github.com/dherges/ng-packagr/issues/85#issuecomment-321256775) in my build process.  I'm planning to release a version today with the fix.  I'll update here when it is released.

**Comment by isaacplmann** [comment]
ngx-tour-ng-bootstrap@1.0.6 should solve this problem.  Let me know if it works for you.

**Comment by KingsDevelopment** [comment]
It worked (: Thanks
