### ISSUE TITLE
Error: importing `TourNgBootstrapModule` into app module

### ISSUE THREAD

**Issue by readelobdill** [isaacplmann/ngx-tour#4]
Hey there,

Installing new version of `@ng-bootstrap/ng-bootstrap` fixes #2!

I am now running into a new error attempting `2) import TourNgBootstrapModule into your app module` from your tutorial site by doing: 
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { TourNgBootstrapModule } from 'ng2-tour/src/lib/plugin/ng-bootstrap/ng-bootstrap.module';

@NgModule({
  imports: [
    CommonModule,,
    TourNgBootstrapModule
  ]
})

export default class AppModule { }
```
I am getting:
`Error: Unexpected value 'TourNgBootstrapModule' imported by the module 'ManagerModule'`

Am I attempting this correctly? Any advice you can offer would be great appreciated, cheers!

**Comment by isaacplmann** [comment]
Try version 0.1.3.  I think its working now.
