### ISSUE TITLE
AOT Compilation Error: import withinviewport from 'withinviewport';

### ISSUE THREAD

**Issue by mustafaekim** [isaacplmann/ngx-tour#41]
I am getting an error when I try to rollup the project (after AOT compiled), when I use ngx-tour. The error is as below. Maybe I should add something in rollup.config.js but I dont know what exactly. 

```ts
[!] Error: 'default' is not exported by node_modules\withinviewport\withinviewport.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules\ngx-tour-md-menu\ngx-tour-md-menu\ngx-tour-md-menu.es5.js (20:7)
18: import { Subject } from 'rxjs/Subject';
19: import { Directionality, MdButtonModule, MdCardModule, MdIconModule, MdMenu, MdMenuModule, MdMenuTrigger, Overlay } from '@angular/material';
20: import withinviewport from 'withinviewport';
           ^
21: var TourState = {};
22: TourState.OFF = 0;
```

**Comment by isaacplmann** [comment]
In my [`ng-package-md-menu.json`](https://github.com/isaacplmann/ngx-tour/blob/master/ng-package-md-menu.json) file I have the following externals declared:

```
      "@angular/cdk": "_angular_cdk",
      "@angular/material": "_angular_material",
      "withinviewport": "withinviewport"
```

These are translated into rollup externals/globals by `ng-packagr`.  I'm definitely out of my depth debugging rollup configs, but hopefully that gives you some direction.
