### ISSUE TITLE
Apply a class to outer MdMenu container

### ISSUE THREAD

**Issue by mmccoy** [isaacplmann/ngx-tour#42]
Any way to add a class to the outer menu container so I can nudge it around from an anchor point?

```
<div class="mat-menu-panel ng-tns-c10-1 tour-step mat-menu-after mat-menu-below ng-trigger ng-trigger-transformMenu" role="menu" ng-reflect-klass="mat-menu-panel" ng-reflect-ng-class="[object Object]" style="opacity: 1; transform: scale(1);"><div class="mat-menu-content ng-trigger ng-trigger-fadeInItems" style="opacity: 1;">
```

Thats the element I would want to apply the class to.

**Comment by isaacplmann** [comment]
You can create a global css rule targeting the `.tour-step` class.  That's a class that `ngx-tour-md-menu` applies to the `<md-menu>` component.

You can create the global css rule in a `styles.css` file or in a component that has `encapsulation: ViewEncapsulation.None`.

Let me know if that works for you.

**Comment by mmccoy** [comment]
Yeah, thats helpful, but for my case I need different nudge properties for each step, so I need to target the rendered MdMenu for each individual step.

I was able to pull it off my using a "shadow" anchor element that I position relatively.. creates an extra dom node, but no big deal -- works fine for my needs.

**Comment by AlexCln** [comment]
Hi Isaac, thanks for your package ! 

I'm try to change the color of the background of the card, no success... 

I already try : 
this:
```
body .cdk-overlay-container .cdk-overlay-pane .mat-card{
   background-color: black !important;
}
```
and this :
```
.tour-step .mat-card{
  background-color: black !important;
}
```
And is it possible to change properties on 'popover' class ? 

Thanks for your attention.

**Comment by isaacplmann** [comment]
Those styles should work if you're declaring them in a global css context (not inside a component's styles that is using the default `ViewEncapsulation.Emulated`).  Where are you declaring those styles?

**Comment by AlexCln** [comment]
Thanks for your quick answer,

This declaration is in a standalone file, and this file is imported directly in my app.component.less.

Should I just make a simple CSS file at the root directory and put my style in there ?

Thanks again
Alexis

**Comment by isaacplmann** [comment]
Yes, either (1) declare the css in a global css file (imported in the index.html) or (2) change the AppComponent's `encapsulation` property to `ViewEncapsulation.None` or (3) put `/deep/` before every css rule that you want to apply globally.

**Comment by AlexCln** [comment]
Thanks you! Issue solved. I create a css file in src/styles/app.tour.css, and I reference it directly in my app.component.less as `@import "styles/app.tour.css";` 

By the way, `/deep/` is recently deprecated by some many browser and it still work without

Thanks again, you save my day
Regards

**Comment by kahboom** [comment]
Is it possible to target specific steps? I thought the `stepId` would do that, but I don't see it added as an `id` or `class` attribute. Perhaps am just doing something wrong.

**Comment by kahboom** [comment]
The reason for the specific target is that the positioning does not appear to be working properly, as I'm lazily loading multiple modules with child components, many of which have a step. As you can imagine, it's proving to be a bit difficult.

**Comment by isaacplmann** [comment]
Putting the step id in a class is a reasonable feature request, I'll add that to my todo list.

But I would like to figure out why your tour steps aren't showing up in the correct place before resorting to a work around.  Can you provide any more context about what your code looks like?

**Comment by AlexCln** [comment]
@kahboom It's look like a CSS properties errors. I've a lot of error on a existing projet a the setup of ngx-tour. Look at this point (these solution worked for me): 

- Wrong position: add `@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';` at the top of your app.component.less.

- Cannot display Icon:  add link tab to your `index.html` :     
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

Have a good day
Alexis
