### ISSUE TITLE
npm install --> ng serve -- ERROR

### ISSUE THREAD

**Issue by michael-roschenwimmer** [isaacplmann/ngx-tour#43]
When trying to do as the title states, it provides errors and doesn't get served to localhost:4200. Are there steps that I am missing? I'm looking to be able to run the source code.

**ERROR STATEMENT BELOW:**

> ERROR in C:/Users/jimmy/angularpractice/ngx-tour-master/src/app/console/console.component.ts (1,29): Cannot find module 'ngx-tour-console'.

> ERROR in C:/Users/jimmy/angularpractice/ngx-tour-master/src/app/console/console.module.ts (4,35): Cannot find module 'ngx-tour-console'.

> ERROR in C:/Users/jimmy/angularpractice/ngx-tour-master/src/app/ng-bootstrap/ng-bootstrap.component.ts (1,29): Cannot find module 'ngx-tour-ng-bootstrap'.

> ERROR in C:/Users/jimmy/angularpractice/ngx-tour-master/src/app/ng-bootstrap/ng-bootstrap.module.ts (4,39): Cannot find module 'ngx-tour-ng-bootstrap'.

> ERROR in Error encountered resolving symbol values statically. Could not resolve ngx-tour-ng-bootstrap relative to C:/Users/jimmy/angularpractice/ngx-tour-master/src/app/ng-bootstrap/ng-bootstrap.module.ts., resolving symbol NgBootstrapModule in C:/Users/jimmy/angularpractice/ngx-tour-master/src/app/ng-bootstrap/ng-bootstrap.module.ts, resolving symbol NgBootstrapModule in C:/Users/jimmy/angularpractice/ngx-tour-master/src/app/ng-bootstrap/ng-bootstrap.module.ts, resolving symbol NgBootstrapModule in C:/Users/jimmy/angularpractice/ngx-tour-master/src/app/ng-bootstrap/ng-bootstrap.module.ts webpack: Failed to compile.

**Comment by isaacplmann** [comment]
I should put in a DEVELOPER.md file.

Try running:
```
npm install
npm run build:lib:all
npm start
```

**Comment by michael-roschenwimmer** [comment]
Hmmmm,

I can't even get to that now... I'm sure I'm just having a user specific issue (and I'm quite a noob in general).

This is the error I am getting when I try to run npm install. Do you have any tips on what I should do to try to remedy the situation?

> $ npm install
> npm WARN The package @angular/compiler-cli is included as both a dev and product                                          ion dependency.
> 
> npm ERR! path C:\Users\jimmy\angularpractice\ngx-tour-master\node_modules\.stagin                                          g\ngx-tour-ng-bootstrap-13cff0e3\node_modules\withinviewport
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\jimmy\angular                                          practice\ngx-tour-master\node_modules\.staging\ngx-tour-ng-bootstrap-13cff0e3\no                                          de_modules\withinviewport' -> 'C:\Users\jimmy\angularpractice\ngx-tour-master\nod                                          e_modules\.staging\withinviewport-372e821a'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\jimmy\AppData\Roaming\npm-cache\_logs\2017-08-29T14_02_44_4                                          > 99Z-debug.log

**Comment by isaacplmann** [comment]
What version of npm are you using? `npm -v`

Try deleting node_modules and the build and starting from scratch:
`rm -rf node_modules package-lock.json dist .ng_build`

**Comment by michael-roschenwimmer** [comment]
I am running npm -v 5.3.0.

This line you gave: 
`rm -rf node_modules package-lock.json dist .ng_build` 

before your initial command steps did the trick. I ran:
```
npm install
npm run build:lib:all
npm start
```
And it worked like a charm.

Thank you for your help with the awesome troubleshooting. I'm sorry if this seemed trivial but it certainly helped me out a lot! And thank you for the cool example of how to incorporate using ng2+.

**Comment by isaacplmann** [comment]
Thanks for asking.  It helps me find holes in my documentation.  File another issue if you need any more help.
