### ISSUE TITLE
Demo doesn't go to other routes

### ISSUE THREAD

**Issue by michael-roschenwimmer** [isaacplmann/ngx-tour#44]
Hello,

After starting the program (using these steps:
```
rm -rf node_modules package-lock.json dist .ng_build
npm install
npm run build:lib:all
npm start
```

)with it being served to localhost everything appears to be working fine. However, "Start Demo Tour" button only seems to work when **MdMenu** is selected. When **NgBootstrap** is selected the "Start Demo Tour" does not start the tour like it does in the live demo. 

Do you have any suggestions?

**Comment by isaacplmann** [comment]
The console tour is designed not to show anything - it only prints messages in the console.  The NgBootstrap tour demo appears to be broken.  I'll look into that.

**Comment by michael-roschenwimmer** [comment]
Sounds good! Thank you.

**Comment by michael-roschenwimmer** [comment]
It looks like the MdMenu tour stops prematurely as well. The bold step is the last place the demo takes you. It seems it is like this on the live demo page as well.

```
   **anchorId: 'config.route',
      content: 'Tours can span multiple routes.',
      title: 'Route',**
    }, {
      anchorId: 'another.route',
      content: 'Like this!',
      route: 'md-menu/other',
      title: 'Another Route',
    }, {
      anchorId: 'config.route',
      content: 'And then back again.',
      placement: 'below',
      title: 'Route Return',
    }, {
      anchorId: 'hotkeys',
      content: 'Try using the hotkeys to navigate through the tour.',
      title: 'Hotkeys',
    }, {
      anchorId: 'events',
      content: 'You can subscribe to events',
      title: 'Events',
    }], {
      route: 'md-menu',
    });
    this.tourService.start();
  }
}
```

**Comment by isaacplmann** [comment]
Should be fixed now.
