### ISSUE TITLE
Not able to install and Use

### ISSUE THREAD

**Issue by SudeepST** [isaacplmann/ngx-tour#5]
Can you please help me with a step by step guide to use ng2-tour. I've followed the tutorial but im not getting any tour when i do this.tourService.start();. I have provided and injected using 
import { TourService } from 'ng2-tour'; and tourService:TourService.

**Comment by isaacplmann** [comment]
Here's [the guide](https://isaacplmann.github.io/ng2-tour/).  Did you do steps 1, 2 and 3?

Can you provide a github repo that reproduces it?  Or paste in parts of your code?

**Comment by mustafaekim** [comment]
Hi, it seems like a good library, thanks for your effort however I could not install either. May be that you can show a demo with systemjs configuration? How should we import TourNgBootstrapModule, are there any dependencies, what lines should I add into systemjs config file?

Thanks

**Comment by isaacplmann** [comment]
Sorry, I've never used SystemJS.  I'd like to make it possible to use it, but I'm not sure how.  I'll open a separate issue for SystemJS support and mark it as help wanted.

**Comment by isaacplmann** [comment]
The systemjs issue is #9 .

**Comment by isaacplmann** [comment]
Systemjs installation should be fixed in `ngx-tour-ng-bootstrap@1.x` and `ngx-tour-md-menu@1.x`
