### ISSUE TITLE
How do I added a tour anchor dynamically?

### ISSUE THREAD

**Issue by JSilva94** [isaacplmann/ngx-tour#50]

**Comment by isaacplmann** [comment]
You can add a tour step dynamically, but I can't think of a good way to add a tour anchor dynamically.  What is your reason for wanting to do that?

**Comment by JSilva94** [comment]
For routing. I pass parameters to the URL, however these parameters arent defined yet on initialize. Should I pass the parameters into my steps array, and then reinitialize?

**Comment by isaacplmann** [comment]
Yes, if you don't know what your anchors will be until runtime, you'll want to update the tour steps once you know what anchor names are.  There is probably a way to dynamically attach a directive to a component at runtime, but it will be a lot more complicated than updating the POJO `steps`.
