### ISSUE TITLE
Showing html as plain text

### ISSUE THREAD

**Issue by Vikram-ksingh** [isaacplmann/ngx-tour#52]
I have integrated it successfully and I am trying to show html in tour box but its showing only plain text with tags as text. Is there a way to show html in tour box ?

**Comment by isaacplmann** [comment]
Angular won't let you inject html as a string in your templates, but you can override the tour step template as described in the "Custom Template" section of the [docs](https://isaacplmann.github.io/ngx-tour/).

If you want to provide a custom template for each step, you could do it like this:

```ts
// app.component.ts  or wherever you initialise your steps
@ViewChild('firstStepTemplate') firstStepTemplate: TemplateRef;
steps = [{
  title: 'First step',
  template: this.firstStepTemplate,
}, {
  title: 'Step with plain text',
  content: 'Some plain text',
}]
```
```html
<!-- app.component.html -->
<ng-template #firstStepTemplate let-step="step">
  This is <strong>html</strong> and you can use <my-custom-component>too</my-custom-component>.  And even reference the step object: {{step.content}}
</ng-template>

<tour-step-template>
  <ng-template let-step="step">
    <md-card (click)="$event.stopPropagation()">
      <md-card-title>
        {{step?.title}}
      </md-card-title>
      <md-card-content>
        <!-- modified part of the tour step template -->
        <ng-container *ngIf="step.template">
          <ng-container *ngTemplateOutlet="step.template; context: { step: step }"></ng-container>
        </ng-container>
        {{step?.content}}
        <!-- end modified part -->
      </md-card-content>
      <md-card-actions>
        <button md-icon-button [disabled]="!tourService.hasPrev(step)" (click)="tourService.prev()">
          <md-icon>chevron_left</md-icon>
        </button>
        <button md-icon-button [disabled]="!tourService.hasNext(step)" (click)="tourService.next()">
          <md-icon>chevron_right</md-icon>
        </button>
        <button md-button (click)="tourService.end()">End</button>
      </md-card-actions>
    </md-card>
  </ng-template>
</tour-step-template>
```

**Comment by jkon** [comment]
I gave this a shot and I am getting this error: Object literal may only specify known properties, and 'template' does not exist in type 'INgxmStepOption'
It doesn't like the template property. Did you remove this feature? If so, is there another way to do it?

**Comment by chriszrc** [comment]
@isaacplmann Well, angular does allow this, using [innerHTML]:

https://www.digitalocean.com/community/tutorials/angular-innerhtml-binding-angular

And supposedly sanitization is built in now. Could this be implemented? It would make the tour templates much easier to customize
