### ISSUE TITLE
Issue using the nextStep field in IStepOption

### ISSUE THREAD

**Issue by dgonzalez870** [isaacplmann/ngx-tour#54]
When set `nextStep = 0` ( go to the first step in the array) in `currentStep`,   it try go to the next step in the array from `currentStep`, for instance

```javascript
[
   ...
   {
      anchorId:  'mtour.anchor',
      content:  'Some content',
      title:  'Test Anchor',
      nextStep: 0
   },
  ...
]

```
It seem caused by this segment of code in __tour.service.ts__

```javascript
  public next(): void {
    if (this.hasNext(this.currentStep)) {
      this.goToStep(this.loadStep(this.currentStep.nextStep || this.steps.indexOf(this.currentStep) + 1));
    }
  }
```

**Comment by isaacplmann** [comment]
You can also use the `stepId` (which defaults to the `anchorId`) to specify the `nextStep` or `prevStep`.

**Comment by dgonzalez870** [comment]
Thanks, it work fine using `stepId`.
