### ISSUE TITLE
Tour starts but no menu

### ISSUE THREAD

**Issue by omnikitty** [isaacplmann/ngx-tour#56]
Hi isaacplmann,
I'm trying to use your module in an ionic app using angular. I've set everything up with the tourAnchors and installed the packages, but when I try to start the tour I don't see anything on my screen. I subscribed to the start and initialize events, which both fire right (the $start IStepOption is undefined, though). 

I compared the demo page to mine and it turns out I'm completely missing the cdk-overlay-container that has the tour text. On the demo, it's here:
<img width="404" alt="screen shot 2017-10-19 at 3 10 38 pm" src="https://user-images.githubusercontent.com/7541670/31758383-d6bb630a-b4df-11e7-9c60-89fb09896a81.png">

I do have the <tour-step-template> in my code but it doesn't have anything displayed. 

Any advice? It could be some other issue as well. I'm using @angular/cdk and @angular/material version 2.0.0-beta.11, because I got some errors with the later versions. Please let me know if you need more info or have any questions. Thanks for making this wonderful library!

**Comment by isaacplmann** [comment]
What does your package.json look like?  I assume you're using the `ngx-tour-md-menu` plugin.

**Comment by omnikitty** [comment]
Yes, I installed ngx-tour-md-menu through npm. Here's my dependencies: 
```
"dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/cdk": "2.0.0-beta.11",
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/compiler-cli": "4.1.2",
    "@angular/core": "4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "^4.4.5",
    "@angular/material": "2.0.0-beta.11",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@angular/router": "^4.4.5",
    "@auth0/cordova": "^0.1.0",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "angular2-elastic": "^0.13.0",
    "angular2-jwt": "^0.2.3",
    "auth0-js": "^8.8.0",
    "auth0-lock": "^10.19.0",
    "bcryptjs": "^2.4.3",
    "cordova-android": "^6.2.3",
    "cordova-ios": "^4.4.0",
    "cordova-plugin-console": "^1.0.7",
    "cordova-plugin-customurlscheme": "^4.3.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-safariviewcontroller": "^1.4.7",
    "cordova-plugin-splashscreen": "~4.0.1",
    "cordova-plugin-statusbar": "2.2.1",
    "cordova-plugin-whitelist": "1.3.1",
    "core-js": "^2.4.1",
    "fs-extra": "^3.0.1",
    "ion2-calendar": "^2.0.10",
    "ionic-angular": "3.3.0",
    "ionic-plugin-keyboard": "~2.2.1",
    "ionic2-autosize": "^1.1.2",
    "ionicons": "3.0.0",
    "moment": "^2.19.1",
    "ngx-tour-md-menu": "^1.0.4",
    "node-sass": "^4.5.3",
    "object-keys": "^1.0.11",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.8.11"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@types/jasmine": "^2.5.41",
    "@types/karma": "^0.13.36",
    "@types/node": "^7.0.8",
    "angular2-template-loader": "^0.6.2",
    "connect": "^3.6.2",
    "html-loader": "^0.4.5",
    "ionic": "3.13.0",
    "jasmine": "^2.5.3",
    "jasmine-spec-reporter": "^4.1.0",
    "karma": "^1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.3",
    "null-loader": "^0.1.1",
    "protractor": "^5.1.1",
    "protractor-fail-fast": "^3.0.2",
    "ts-loader": "^2.0.3",
    "ts-node": "^3.0.2",
    "typescript": "2.3.3"
  },
```

**Comment by isaacplmann** [comment]
Your `@angular/something` dependencies should all be using the same version except for `@angular/cdk` and `@angular/material`.  I don't know if that's causing this issue, but it will definitely cause issues.

**Comment by omnikitty** [comment]
Thanks for the tip! They are now all at 4.1.2 (except for cdk and material).
<img width="471" alt="screen shot 2017-10-28 at 2 59 33 pm" src="https://user-images.githubusercontent.com/7541670/32132143-ac4d9436-bbf0-11e7-9691-8f0a616ecdb8.png">

This error now comes up. I don't know if that has anything to do with the issue as it's just a warning, but who knows. I've tried looking it up but the solutions are for angular cli users and don't work for me.

`<link href="node_modules/@angular/material/prebuilt-themes/indigo-pink.css" rel="stylesheet">` is what I put in my index.html for material as per the link. 
I'm wondering if it's an ionic issue or just incompatible? Any ideas?
Thanks again!

**Comment by isaacplmann** [comment]
It looks like your node_modules folder is not being served up by the web server.  You could try copying that css theme file to an assets folder and referencing it from there.  Not having the css file loaded will definitely make the tour not show up correctly.

**Comment by isaacplmann** [comment]
Here's the official material documentation on adding the theme file:
https://material.angular.io/guide/getting-started#step-4-include-a-theme
