### ISSUE TITLE
tourService.start() emits tourService.end()

### ISSUE THREAD

**Issue by kulmann** [isaacplmann/ngx-tour#57]
I have set up a tour following your demo source for ng-bootstrap. I added four steps which seem to be recognized, as I am able to call e.g. startAt(1) at it doesn't complain about non-existent steps. I start the tour automatically and have a button to toggle the tour. As shown in the example I have subscribed to the events of the tourService so I can see that a start or resume event is always followed by and end event immediately. Like this:
`{name: "start", value: undefined}`
`{name: "end", value: undefined}`
Do you have any idea where to start further debugging? The popup doesn't show but there is no error at all, only the end-event right after each start or resume event.

**Comment by isaacplmann** [comment]
I would put a console.log where you are calling `tourService.start()` to make sure that you're not calling it twice.  Also, are you calling `tourService.initialise()` with the steps?

**Comment by kulmann** [comment]
Thanks for your reply! My code looks like this:
`this.tourService.events$.subscribe(console.log);`
`    this.tourService.initialize([{`
`      anchorId: "dashboard.first",`
`      content: "This is an interactive tour.",`
`      title: "Welcome",`
`      route: "pages/dashboard"`
`    }, {`
`      anchorId: "dashboard.second",`
`      content: "Look at this beautiful chart.",`
`      title: "Chart 1",`
`      route: "pages/dashboard"`
`    }, {`
`      anchorId: "dashboard.third",`
`      content: "And here is another one!",`
`      title: "Chart 2",`
`      route: "pages/dashboard"`
`    }]);`
`    console.log("before start");`
`    this.tourService.start();`
`    console.log("after start");`

The console output is:
`{name: "initialize", value: Array(3)}`
`app.component.ts:59 before start`
`Subscriber.js:238 {name: "start", value: undefined}`
`app.component.ts:61 after start`
`Subscriber.js:238 {name: "end", value: undefined}`
Any ideas?

**Comment by isaacplmann** [comment]
Try taking the `route` property off of all the steps.  It might be ending the tour when it can't navigate to that route.

**Comment by isaacplmann** [comment]
Actually, that's probably not the problem.  It's ending the tour because it can't find an anchor with an anchorId that matches the first step.  The `tourAnchor` directive will automatically register itself in the `ngOnInit` method.

**Comment by kulmann** [comment]
Ok, my html template for the dashboard looks like this (ba-card is a custom component which uses a bootstrap card):

`<div class="row">`
`  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">`
`    <pie-chart tourAnchor="dashboard.first"></pie-chart>`
`  </div>`
`</div>`
`<div class="row">`
`  <ba-card class="col-xlg-6 col-xl-6 col-lg-12 col-sm-12 col-12" cardTitle="dashboard.acquisition_channels" baCardClass="traffic-panel medium-card">`
`    <traffic-chart tourAnchor="dashboard.second"></traffic-chart>`
`  </ba-card>`
`  <ba-card class="col-xlg-6 col-xl-6 col-lg-12 col-md-6 col-sm-12 col-12" cardTitle="dashboard.revenue" baCardClass="medium-card">`
`    <line-chart tourAnchor="dashboard.third"></line-chart>`
`  </ba-card>`
`</div>`

Is there anything else I need to do to declare tourAnchors?

**Comment by isaacplmann** [comment]
That should be right.  Add this line before the `tourService.start()`
```
console.log(this.tourService.anchors);
```

**Comment by isaacplmann** [comment]
Maybe the `tourAnchor`s have not hit their `ngOnInit` hook yet.  Where are you calling `tourService.start()`?

**Comment by kulmann** [comment]
Your guess is correct, `this.tourService.anchors` is empty at the start() call. I have placed both the initialize([]) and the start() calls within the constructor of my app.component.ts. But even if I move them to `ngAfterContentInit()` the anchors are still empty. I will try to get that right tomorrow... thanks a lot for your help so far!

**Comment by RetoRechsteiner** [comment]
Same Problem here, The anchors are still empty. You found a solution?
We have one abstraction more. An App.Module and a Layout.Module with the Shell.Component. In the Shell.Component we have the router-outlet. But the Tour-Code is still in the App.Component is that right?

**Comment by isaacplmann** [comment]
@RetoRechsteiner 
The tour steps being initialized in the app component is fine.  It's hard for me to debug your app without seeing code.  Can you make a git hub repository that reproduces the issue?  Or you can sign up for a (paid) session with me on [codementor](https://www.codementor.io/isaacplmann?utm_source=github&utm_medium=button&utm_term=isaacplmann&utm_campaign=github) and I can look directly at your app code.

**Comment by kulmann** [comment]
My colleague found a solution for this problem: you need to import the tour module (in our case TourNgBootstrapModule) in each and every sub module.

**Comment by isaacplmann** [comment]
I'm glad you found a solution.

**Comment by sachin0396** [comment]
Same Issue .. i have done all the steps provided by @kulmann .. still getting 
{name: "start", value: undefined} 
{name: "end", value: undefined}
Help me out!!!
