### ISSUE TITLE
how use it in ionic 3

### ISSUE THREAD

**Issue by Benoit-ROBIN** [isaacplmann/ngx-tour#58]
Hi sorry for my english
I try to use your library in my ionic 3 projet.
I follow your doc but I can't make it works .

 - I install npm install ngx-tour-md-menu @angular/animations @angular/cdk @angular/http @angular/material
 - import TourMatMenuModule.forRoot() into my app module
 - I import RouterModule is my app module
- I add <tour-step-template></tour-step-template> to my root app component
- I add tourAnchor="some.anchor.id" on elem into my HomeComponent wich is the first and only  component load after my root app component
- In my HomeComponent I define  tour steps using tourService.initialize(Object with my steps)
 - Start the tour with tourService.start()

In console I have "ERROR Error: No provider for Router!" 
App module
`@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    RouterModule,
    TourMatMenuModule.forRoot(),
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    TourService,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})`

HomeComponent
`@Component({
  selector: "page-home",
  templateUrl: "home.html"
})
export class HomePage {

  constructor(public navCtrl: NavController, public tourService: TourService) {

    this.tourService.initialize([{
      anchorId: 'some.anchor.id',
      content: 'Some content',
      title: 'First',
    }, {
      anchorId: 'another.anchor.id',
      content: 'Other content',
      title: 'Second',
    }]);

    this.tourService.start();
  }

}`

**Comment by Benoit-ROBIN** [comment]
I resolve my problem ;), but I don't understand why I have to define a RouterModulein my app.module.

**Comment by isaacplmann** [comment]
The tour library uses the router to go to the next step if that step is on a different route.  It probably would be good to make that an optional dependency for people that don't want to use that feature.
