### ISSUE TITLE
step stay on top left

### ISSUE THREAD

**Issue by Benoit-ROBIN** [isaacplmann/ngx-tour#59]
Hi 
After severals brains explosions I succesfully install your library on my ionic project and it works except for "step card" placement. They stay on top left of the screen instead of follow the element wich they are linked. I didn't read anything in your doc about that.

package.json 
`"dependencies": {
    "@angular/animations": "4.4.4",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/compiler-cli": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@ionic-native/core": "4.3.2",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "4.3.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.8.0",
    "ionicons": "3.0.0",
    "ngx-tour-md-menu": "^2.0.0-beta.12",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  }`

angular/animations core http are in 4.4.4,
angular/material and cdk are in 2.0.0-beta.12

**Comment by isaacplmann** [comment]
That's probably something with the styles.  Do you include the angular/material theme?  Do you set a doctype on your `index.html`?  Inspect the `div.cdk-overlay-container` element at the foot of the body.  What is it's position css value?  What about the `.cdk-overlay-pane` inside of it? Does the pane have correct top and left values?

**Comment by Benoit-ROBIN** [comment]
position: absolute on .cdk-overlay-pane was missing. 
Thanks for your help.
