### ISSUE TITLE
HotkeyOptions from angular2-hotkeys giving an error

### ISSUE THREAD

**Issue by tushar93** [isaacplmann/ngx-tour#6]
This is the error that webpack throws:
**core_1.InjectionToken is not a constructor**

Please find attached image file :

![ng2-tour_error](https://cloud.githubusercontent.com/assets/26000051/23353766/213d2dae-fcf4-11e6-8e55-a23d4b6ebaf2.png)

**Comment by isaacplmann** [comment]
I know exactly what that problem is. I need to pin my dependency on
angular2-hotkeys to 1.x. 2.x is for angular v4+. I'll fix it in a few hours
when I get to work.

**Comment by tushar93** [comment]
Thanks so much ! Please let me know when its fixed :-)

**Comment by isaacplmann** [comment]
I published 0.1.4 that should require angular2-hotkeys to be only 1.x instead of 2.x.  If you're still having issues, check the package.json in your own app to make sure you're not importing the 2.x version of angular2-hotkeys.

**Comment by tushar93** [comment]
Hi, thanks but it still is not working , I checked my package.json and i changed the angular2-hotkeys 2.x to 1.x version.
![app-tour1](https://cloud.githubusercontent.com/assets/26000051/23403913/6843c246-fdd8-11e6-9a35-f2f8ff518373.png)

**Comment by isaacplmann** [comment]
I reproduced the problem on the demo app.  Try again with version 0.1.5.

**Comment by tushar93** [comment]
still not working

**Comment by isaacplmann** [comment]
Have you tried deleting your node_modules folder and running npm install
again?

If that doesn't work I'll need more information about your code. Send me
your package.json file and tell me how you're importing modules.

**Comment by isaacplmann** [comment]
Are you still having this problem?

**Comment by sh977218** [comment]
I'm using 
angular: 4.1.3
webpack: 2.6.1
This issue is still exist.
This is the error:
`(1,32): error TS2307: Cannot find module 'angular2-hotkeys'.
ERROR in ./~/ng2-tour/src/lib/tour.module.js
Module not found: Error: Can't resolve 'angular2-hotkeys' in 'c:\NLMCDE\cde\node_modules\ng2-tour\src\lib'
 @ ./~/ng2-tour/src/lib/tour.module.js 9:25-52
 @ ./modules/app.module.ts
 @ ./modules/main.ts`

**Comment by isaacplmann** [comment]
> I'll need more information about your code. Send me
your package.json file and tell me how you're importing modules.

Thanks!

**Comment by sh977218** [comment]
here is the package.json
`{
  "name": "ludetc-cdes",
  "version": "0.0.1",
  "scripts": {
    "build": "cross-env BUILD_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js",
    "start": "node app.js",
    "dev": "rm -f modules/static/main.js.map modules/static/print.js.map modules/static/embed.js.map && node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js"
  },
  "engines": {
    "node": "0.12.x",
    "npm": "1.2.x"
  },
  "dependencies": {
    "JSONStream": "0.10.0",
    "archiver": "1.3.0",
    "async": "0.9.0",
    "body-parser": "1.11.0",
    "byline": "4.2.1",
    "chalk": "*",
    "clamav.js": "0.11.0",
    "compression": "1.6.0",
    "config": "*",
    "connect-flash": "0.1.1",
    "connect-mongo": "1.3.2",
    "cookie-parser": "1.3.3",
    "cron": "1.0.9",
    "csurf": "1.9.0",
    "csv": "0.4.6",
    "csv-parser": "1.11.0",
    "deep-copy": "1.0.0",
    "deep-diff": "0.3.0",
    "ejs": "1.0.0",
    "elasticsearch": "13.0.1",
    "event-stream": "3.3.0",
    "express": "4.11.2",
    "express-ipfilter": "0.0.25",
    "express-session": "1.15.0",
    "fstream": "1.0.4",
    "gridfs-stream": "1.1.0",
    "helmet": "2.1.0",
    "http-proxy": "1.16.2",
    "js2xmlparser": "1.0.0",
    "jxon": "2.0.0-beta.2",
    "log-buffer": "0.0.3",
    "md5": "2.2.1",
    "md5-file": "3.1.1",
    "method-override": "2.3.1",
    "moment": "2.17.1",
    "mongoose": "4.9.6",
    "morgan": "1.5.1",
    "multer": "0.1.7",
    "nodemailer": "1.3.0",
    "passport": "0.2.1",
    "passport-local": "1.0.0",
    "passport-oauth": "1.0.0",
    "passport.socketio": "3.7.0",
    "request": "2.79.0",
    "serve-favicon": "2.2.0",
    "shortid": "2.1.3",
    "socket.io": "1.4.5",
    "streamifier": "0.1.1",
    "tar-fs": "0.5.2",
    "trim": "0.0.1",
    "winston": "0.9.0",
    "xml2js": "0.4.17",
    "xmlbuilder": "2.6.2",
    "xsd-schema-validator": "0.5.0",
    "mongoose-schema-jsonschema": "1.1.13",
    "lodash": "4.17.4"
  },
  "devDependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/router": "4.1.3",
    "@angular/upgrade": "4.1.3",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.25",
    "@ngtools/webpack": "1.4.1",
    "@types/node": "7.0.5",
    "angular2-template-loader": "0.6.0",
    "angular-2-local-storage": "1.0.1",
    "angular-tree-component": "3.7.3",
    "babel-polyfill": "6.22.0",
    "bootstrap": "4.0.0-alpha.6",
    "capitalize": "1.0.0",
    "codelyzer": "2.0.0",
    "core-js": "2.4.1",
    "cross-env": "3.1.4",
    "css-loader": "0.26.1",
    "entities": "1.1.1",
    "es6-promise": "*",
    "file-loader": "0.9.0",
    "gulp": "3.9.1",
    "gulp-angular-templatecache": "1.8.0",
    "gulp-bower": "0.0.11",
    "gulp-clean-css": "2.3.2",
    "gulp-concat": "2.6.0",
    "gulp-cssnano": "2.1.0",
    "gulp-git": "1.7.0",
    "gulp-header": "1.8.2",
    "gulp-install": "0.6.0",
    "gulp-npm-files": "0.1.3",
    "gulp-rev": "6.0.1",
    "gulp-run": "1.7.1",
    "gulp-uglify": "1.5.1",
    "gulp-usemin": "0.3.27",
    "gulp-wiredep": "0.0.0",
    "jasmine-reporters": "2.2.1",
    "json-beautify": "1.0.1",
    "lodash": "4.17.4",
    "ng-diff-match-patch": "https://github.com/sh977218/ng-diff-match-patch.git",
    "ngx-bootstrap": "2.0.0-beta.2",
    "ng2-ckeditor": "1.1.7",
    "ng2-select2": "1.0.0-beta.10",
    "protractor": "5.1.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.9",
    "protractor-jasmine2-html-reporter": "0.0.7",
    "rxjs": "5.2.0",
    "selenium-webdriver": "3.4.0",
    "style-loader": "0.13.1",
    "tar": "2.1.0",
    "ts-loader": "2.0.0",
    "tslint": "4.4.1",
    "tslint-loader": "3.3.0",
    "typescript": "2.2.2",
    "webpack": "2.6.1",
    "zone.js": "0.8.12",
    "ng2-tour": "0.1.7"
  }
}
`

Here is how I import the modules
`//import { TourModule } from 'ng2-tour/src/lib/tour.module';
import { TourNgBootstrapModule } from 'ng2-tour/src/lib/plugin/ng-bootstrap/ng-bootstrap.module';

@NgModule({
    declarations: [
    ],
    providers: [],
    imports: [
        TourNgBootstrapModule
//        TourModule
    ],
    bootstrap: [CdeAppComponent]
})
export class CdeAppModule {
}
`

**Comment by isaacplmann** [comment]
`angular2-hotkeys` is not a dependency for `ngx-tour-ng-bootstrap@1.x` and `ngx-tour-md-menu@1.x`

**Comment by di3orlive** [comment]
@isaacplmann i have same problem 
and what is solution ?

**Comment by isaacplmann** [comment]
Tomorrow I'm planning to update the documentation with instructions for installing version 1.x.  Since `angular2-hotkeys` is not a dependency in version 1.x, you won't see this error.

**Comment by di3orlive** [comment]
@isaacplmann cool, tnx

**Comment by di3orlive** [comment]
@isaacplmann any news?

**Comment by isaacplmann** [comment]
No news yet, I just got to work.  I'm working on the documentation today.

**Comment by di3orlive** [comment]
@isaacplmann mb i can help somehow ?

**Comment by isaacplmann** [comment]
I'm getting stuck on issue #30 .  I don't recommend launching into version 1.x until that is fixed.  Working on it again today.

**Comment by isaacplmann** [comment]
Finally fixed that issue.  Check out the new [documentation](https://isaacplmann.github.io/ngx-tour/).

**Comment by jorgekg** [comment]
Add on import of test, `HotkeyModule.forRoot()`
