### ISSUE TITLE
How to toggle CSS dimmable background linear-gradient

### ISSUE THREAD

**Issue by einewton** [isaacplmann/ngx-tour#61]
Hello,

Thank you for your support and work on this plugin. How to turn on the background gradient opacity to darken the background and focus the users attention to the tour, and also highlight your element?

This is doable in the bootstrap version and the angular 1 version, but how do you accomplish this within this plugin ngx-tour?

**Comment by isaacplmann** [comment]
Which `ngx-tour` plugin are you using? `ngx-tour-md-menu`, `ngx-tour-ng-bootstrap`, or `ngx-tour-ngx-bootstrap`?

**Comment by einewton** [comment]
I could not find it in any of them. Also looking at the examples, I do not see it either.

**Comment by isaacplmann** [comment]
Yes, it's not in the examples - but my answer on how to do it depends on which plugin you're using.

**Comment by einewton** [comment]
I am using Angular 4.4.6 and have not yet implemented this into my solution - If this is possible to do, what would you recommend I use to accomplish highlighted elements?

**Comment by isaacplmann** [comment]
If you use `ngx-tour-md-menu`, you can add this css:

```css
.cdk-overlay-backdrop {
  background: black;
}
```

There are probably ways to do the same thing with the other plugins too.

**Comment by edwarfuentes97** [comment]
I have the same problem... i need a class for ngx-tour-ngx-bootstrap . can u please help me with that ?

**Comment by isaacplmann** [comment]
I don't think `ngx-bootstrap` provides a way to do that.  See their [popover documentation](https://valor-software.com/ngx-bootstrap/#/popover).

**Comment by Kailiangdong** [comment]
> .cdk-overlay-backdrop { background: black; }

May I ask where I should add this css? In app.component.css or style.css? Thank you very much

**Comment by isaacplmann** [comment]
style.css would be the easiest place to put it.

**Comment by dws-tushargupta** [comment]
> I have the same problem... i need a class for ngx-tour-ngx-bootstrap . can u please help me with that ?
> i´m using a implementation in angular 5, and this working so fine , but i need a background customisable

I am having the same issue, using `ngx-tour-ngx-bootstrap` with Angular 5 & need backdrop effect. Can U please help me with that?

**Comment by dws-tushargupta** [comment]
> I have the same problem... i need a class for ngx-tour-ngx-bootstrap . can u please help me with that ?
> i´m using a implementation in angular 5, and this working so fine , but i need a background customisable

I am having the same issue, using `ngx-tour-ngx-bootstrap` with Angular 5 & need backdrop effect. Can U please help me with that?

**Comment by chriszrc** [comment]
Would be great to have this for the ngx-popper as well. Or if angular would just let us add arrows to the mat-menu and we wouldn't need ngx-popper anymore 🤦‍♂️
