### ISSUE TITLE
AOT Compilation error

### ISSUE THREAD

**Issue by kelvinmbwilo** [isaacplmann/ngx-tour#62]
I am failing to build by AOT 

Package.json:
"angular/animations": "^4.4.6",
 "angular/common": "^4.4.6",
 "angular/compiler": "^4.4.6",
 "angular/core": "^4.4.6",
 "angular/forms": "^4.4.6",
 "angular/http": "^4.4.6",
 "angular/platform-browser": "^4.4.6",
"angular/platform-browser-dynamic": "^4.4.6",
"angular/router": "4.3.1",
"ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
"ngx-tour-ng-bootstrap": "^2.0.0-beta.5-1",

After build I am getting the following error
ERROR in /home/kelvin/development/newDevs/scorecard/src/$$_gendir/node_modules/ngx-tour-ng-bootstrap/node_modules/ngx-tour-core/ngx-tour-core.ngfactory.ts (10,21): Cannot find module 'ngx-tour-core'.

ERROR in /home/kelvin/development/newDevs/scorecard/src/$$_gendir/app/app.module.ngfactory.ts (27,22): Cannot find module 'ngx-tour-core'.

ERROR in /src/$$_gendir/app/shared/shared.module.ngfactory.ts (26,22): Cannot find module 'ngx-tour-core'.

ERROR in /src/$$_gendir/app/create/create.module.ngfactory.ts (27,22): Cannot find module 'ngx-tour-core'.

ERROR in /src/$$_gendir/app/view/view.module.ngfactory.ts (27,22): Cannot find module 'ngx-tour-core'.

**Comment by isaacplmann** [comment]
What are you using to build your app? Angular cli, custom webpack, system
js?

I'm on vacation until Monday. I'll get back to you then.

**Comment by kelvinmbwilo** [comment]
I am using angular cli V1.4.x

**Comment by isaacplmann** [comment]
I just tried setting up a sample app with those same dependencies and I don't get that error.

Try deleting your `node_modules` folder and `package.lock.json` and rerunning `npm install`.  Also, you `@angular/router` version should be the same as the rest of your angular dependencies.

**Comment by kelvinmbwilo** [comment]
Thanks, it worked after deleting package.lock.json
