### ISSUE TITLE
Option to disable keyboard shortcuts

### ISSUE THREAD

**Issue by bkoot** [isaacplmann/ngx-tour#64]
Hello,

Thank you for the nice and easy to use component (and the only one for angular 2+ as far as I can tell).

I am trying to integrate ngx-tour-md-menu into a project. The project allows the user to pan a map using arrow keys. ngx-tour also listens for the arrow keys which leads to the map panning en the tour going to the next or previous step when the user presses an arrow key.

Is it possible to provide an option to disable the use of keyboard shortcuts in the tour component? 

If you like the idea but don't have time to implement it, I can give it a go and provide a pull request.

**Comment by isaacplmann** [comment]
Yes, good idea. PR welcome. I'd add a Boolean to tour service and then
check it in the hot key listener component.
