### ISSUE TITLE
Unable to get anchorId outside component

### ISSUE THREAD

**Issue by dhodo** [isaacplmann/ngx-tour#65]
Hi,

First of all, @isaacplmann thanks for your work!

I am having a bad time trying to get the anchorId which is outside the component where I initialize my tourService. I console log all the anchors and the one outside the component is there, but when i initialize the tourService it doesn't get it. What am I doing wrong?

Thanks!!

**Comment by dhodo** [comment]
I just discovered that I needed to import TourMatMenuModule in that module where the anchorId is, sorry!

**Comment by saurabhchandrapatel** [comment]
you need to import this  "TourMatMenuModule" on every component

![image](https://github.com/user-attachments/assets/0991c363-6dae-4dcc-b5fc-64009cd627f6)


check this here - https://hakimio.github.io/ngx-ui-tour/md-menu/Setup
