### ISSUE TITLE
Showing the courage to ask for help - "Cannot set property 'step' of undefined"

### ISSUE THREAD

**Issue by raymondtri** [isaacplmann/ngx-tour#68]
So I am getting a `Cannot set property 'step' of undefined` error once I tell the tourService to start.

However, when I run 
```
		this.tourService.initialize$.subscribe((steps: IStepOption[]) => {
			console.log('tour configured with these steps:', steps);
			//this.tourService.start();
		});
		this.tourService.initialize([{
			anchorId: 'some.anchor.id',
			content: 'Some content',
			title: 'First',
		}, {
			anchorId: 'another.anchor.id',
			content: 'Other content',
			title: 'Second',
		}]);
```
I get
![image](https://user-images.githubusercontent.com/14185938/33394958-feb06106-d511-11e7-86da-53af7d0c39a7.png)

Is this just related to the order in which it is loading? I am anchoring the directive as follows:
![image](https://user-images.githubusercontent.com/14185938/33395144-92f960ba-d512-11e7-9e0d-4c33e9a520b2.png)

**Comment by isaacplmann** [comment]
That error would happen if the tour service can't find the `<tour-step-template>`.  Are you including that?

**Comment by raymondtri** [comment]
Yes, I am including it in the index.html. Is that the proper area? Or should I be including it on each individual page?
`  
  <ion-app><tour-step-template></tour-step-template></ion-app>`

**Comment by isaacplmann** [comment]
No, `index.html` is outside of Angular's knowledge so the service can't find it.  The easiest place to put it would be inside `app.component.html`.

**Comment by raymondtri** [comment]
Should the entire existing code be wrapped in it? Or does it just need to be placed somewhere on the page. I'm still slightly confused as to how this should work. I see in the demo that you have the router outlet in demo.component.html.

**Comment by raymondtri** [comment]
Got it, thanks. Sorry about the hassle.

**Comment by isaacplmann** [comment]
No problem.  Glad to help.
