### ISSUE TITLE
Infinite loop - call stack exceeded crashing app

### ISSUE THREAD

**Issue by raymondtri** [isaacplmann/ngx-tour#69]
The use case is that I am doing a soft prompt before requesting to use geolocation services and then load in results based on the geoposition after the geolocation services have been initiated.

```
		this.tourService.stepHide$.subscribe((step: IStepOption) => {
			//hook into stepHide to pause the tour once soft prompts have been shown
			if(step.anchorId == 'guide.motionsoftprompt'){
				this.tourService.end();
				this.locationTracker.lateStart();
			}
		});
```

The problem is that this event occurs an infinite number of times (until the maximum call stack size is exceeded). Is this because when the tourService is called to .end() it never completed the stepHide event? Should there be another way to implement this? I have also tried this.tourService.pause() and the same thing happens.

**Comment by isaacplmann** [comment]
I think both `tourService.end()` and `tourService.pause()` will trigger another `stepHide` event - which will trigger another loop.  Try subscribing to `stepShow$` instead.  My guess is that it won't even flicker for the user before the `tourService.end()` hides it.

**Comment by raymondtri** [comment]
You're exactly right, that was the issue. There also is no flicker in testing, that was my original worry with subscribing to the `stepShow$` instead of `stepHide$` thanks.
