### ISSUE TITLE
Feature request: skip unregistered anchors

### ISSUE THREAD

**Issue by kulmann** [isaacplmann/ngx-tour#70]
We would like to define view-specific tours where in some cases there is an empty list with an info text (e.g. "There are no list items, yet.") and in other cases there are actual list items. I would like to set up a tourAnchor on the empty-list-info and one on the first actual list entry. When I register both, I have the problem that the tour stops at the first unsuccessfully registered anchor (which exists in any case because the two anchors can't exist at the same time). It would be nice to have a configuration option for the tour service which let's you automatically skip unregistered anchors instead of stopping the tour. I know that the hasNext() method won't work on that items properly anymore, but that is not a problem.

**Comment by isaacplmann** [comment]
That sounds like a good feature.  Would you like to try your hand at a PR?  This would be a change to the `TourService` inside of `ngx-tour-core`.  I can help give you direction if you need it.

Another option (without the need for a PR) is to call `tourService.initialize(..)` multiple times.  Whenever the state of your app changes such that the steps should change, you can call `tourService.initialize()` again with the new steps.

**Comment by halilibrahim** [comment]
Another hacky option is overriding the showStep method as below
```ts
this.tourService['showStep'] = function (step): void {
  const anchor = this.anchors[step && step.anchorId];
  if (!anchor) {
    console.warn('Can\'t attach to unregistered anchor with id ' + step.anchorId);
    // this.end();
    this.next();
    return;
  }
  anchor.showTourStep(step);
  this.stepShow$.next(step);
};
```

**Comment by damo1884** [comment]
Ended up using this

```
this.tourService['register'] = function (anchorId, anchor): void {
            if (this.anchors[anchorId]) {
                //throw new Error('anchorId ' + anchorId + ' already registered!');
            }
            this.anchors[anchorId] = anchor;
            this.anchorRegister$.next(anchorId);
        };
```
