### ISSUE TITLE
Does this support older version of Angular Material with `md` namespace ?

### ISSUE THREAD

**Issue by ashishgaikwad** [isaacplmann/ngx-tour#71]
I would like to integrate ngx-tour in a existing Angular project which is using an older version of Angular Material with `md` namespace components. Would like to know if they are supported or if new `mat` namespace is mandatory.

**Comment by isaacplmann** [comment]
Not supported in the latest version but you can go back to an older version
that does support it. I'll check which one on Tuesday if you haven't
figured it out by then.

**Comment by isaacplmann** [comment]
You want version `ngx-tour-md-menu` version 1.0.4.

**Comment by AaronLavers** [comment]
Hey @isaacplmann , I'm also trying to run this in an existing MD project- however usion version 1.0.4 returns the error  Failed to compile: /node_modules/ngx-tour-core/tour.service.d.ts (23,56): ',' expected.

**Comment by isaacplmann** [comment]
I created a test app that works normally with the following versions:

```
    "@angular/cli": "1.4.x",
    "ngx-tour-md-menu": "^1.0.4",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/cdk": "^2.0.0-beta.10",
```

There's no need to include `ngx-tour-core` directly in your `package.json`.  If you're still having issues, please share your package.json file.  Also sometimes removing `node_modules` and `package-lock.json` and rerunning `npm install` can resolve issues.
