### ISSUE TITLE
[Feat req] ngx-tour without third party UI framework

### ISSUE THREAD

**Issue by ScottSpittle** [isaacplmann/ngx-tour#75]
Brilliant library, however if you are one of the many people that do not use any of the UI frameworks utilized here then you are unable to use this product.

Any chance you can implement the ability to have custom classes that do not require a UI framework.

**Comment by isaacplmann** [comment]
You want ngx-tour-core. You can check out the code for ngx-tour-console to
see how to wire up your own widgets.

**Comment by ScottSpittle** [comment]
@isaacplmann Ok I'll give it a go. I assumed it wasn't possible as it didn't contain the template

**Comment by isaacplmann** [comment]
Now that I'm at my desk I can give you a more thorough answer.

First, I think it's great that you're trying to use this library with your own custom components.  Please report back how it goes so other people could do the same.

Second, let me explain the architecture of the ngx-tour system.

Each of the ui library versions of the library uses `ngx-tour-core` under the hood.

`ngx-tour-core` provides the `TourService`, `TourAnchorDirective` and a few other common pieces of functionality.  The `TourService` is basically a manager for the tour state and provides hooks for the UI layer to know which step it should be showing at a given time.

Each of the UI libraries provide two things. (1) Popover positioning and (2) styling/UI for the popover.  Writing your own styling/UI component is pretty straight forward.  Writing your own popover positioning code is very difficult and should be handed off to someone else who can maintain it for you.

If all you want is to change the (2) styling/UI, I would recommend using one of the UI libraries and just overwriting the `<tour-step-template>`.

Let me know if you have any questions.

**Comment by seanmavley** [comment]
@isaacplmann 

> If all you want is to change the (2) styling/UI, I would recommend using one of the UI libraries and just overwriting the <tour-step-template>.

What if my UI library of choice has their own positioning? 

I want to have ngx tour using the ui Kit UI for it. They seem to have the bootstrap popover thing too: https://getuikit.com/assets/uikit/tests/dropdown.html

If I get your steps right:

 - I install `ngx-tour-core`
 - Add `TourModule` to my `app.module.ts` or whatever module i'll be using in.
 - I add the `<tour-step-template>` to my root app component
 - And then?

the above steps are what I tried, however, it complains of no <tour-step-template> known.

Perhaps you could point me to some form of documentation explaining how to get this going?

**Comment by isaacplmann** [comment]
@seanmavley If your UI library has its own positioning, you will want to implement your own version of `ngx-tour-ng-bootstrap`, `ngx-tour-md-menu` or `ngx-tour-ngx-bootstrap`.  PR #48 is where `ngx-tour-ngx-bootstrap` was added.  The conversation there might be helpful.

If your UI library is particularly light weight, you might be able to just implement something like `ngx-tour-console`.

Can you paste the exact error you're getting?
