### ISSUE TITLE
AOT compilation error

### ISSUE THREAD

**Issue by mharini** [isaacplmann/ngx-tour#78]
The application fails when built by AOT, I am getting the following error when tourService.start() is called.

`Error: No component factory found for PopoverContainerComponent.`

How to resolve this issue?

**Comment by isaacplmann** [comment]
What versions of each package are you using?  Just paste in the `dependencies` section of your `package.json`.

**Comment by mharini** [comment]
Below is the dependencies I am using in my application.

`"@angular-devkit/core": "0.0.28",
    "@angular/animations": "^5.2.1",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/material": "^5.1.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "5.0.0",
    "bootstrap": "4.0.0-beta.2",
    "ngx-bootstrap": "^2.0.0-beta.8",
    "ngx-tour-ngx-bootstrap": "^2.0.0-beta.9"`

**Comment by isaacplmann** [comment]
`ngx-tour-ngx-bootstrap@2.0.0-beta.9` requires `ngx-bootstrap` to be `2.0.0-beta.9` or higher.

Also, all the `@angular` packages besides `cdk` and `material` should be on the same version.  That's probably not causing this problem, but it will cause other problems eventually.

**Comment by mharini** [comment]
I changed the version numbers and re-installed the packages again.

But as you said, this did not solve the AOT issue. Any other suggestions to resolve the issue?

**Comment by isaacplmann** [comment]
Can you share a simple github repo that reproduces this behavior?

**Comment by isaacplmann** [comment]
This should be fixed in `ngx-tour-ngx-bootstrap@2.0.0`
