### ISSUE TITLE
No indication which element the popup is is for

### ISSUE THREAD

**Issue by damien-murphy** [isaacplmann/ngx-tour#79]
Is there a way to show a directional arrow to show which element the popover is for?

**Comment by isaacplmann** [comment]
`ng-bootstrap` and `ngx-bootstrap` have that functionality.  Material doesn't.  Material tries to handle that by animating the popup when it opens, but after it is open, you can't really tell which element it is anchored to.  That's something that the underlying UI library takes care of.  I can't really fix that.

**Comment by damien-murphy** [comment]
Since we are not using Bootstrap in our project adding it just for an arrow seems like overkill

Is there a light weight way to achieve this without Bootstrap?

**Comment by isaacplmann** [comment]
I don't know of a good way to do that.  You may find some help searching the angular material issues.

**Comment by damo1884** [comment]
This is resolved by ngx-tour-ngx-popper https://github.com/isaacplmann/ngx-tour/pull/85
