### ISSUE TITLE
Is it possible to highlight the correspondending anchorPoint?

### ISSUE THREAD

**Issue by fenta23** [isaacplmann/ngx-tour#81]
Feature Request:

Can i mark the tourAnchor somehow as highlighted? a class would be enough. 

What do you think?

And i have to say: 
Really nice project, took me a while to get it working, but now the TourMatMenuModule works smoothly in Angular@5.x.x

Thanks, Micha.

**Comment by isaacplmann** [comment]
That's a great idea and pretty easy to implement.  I hope to do this today.

**Comment by fenta23** [comment]
Thanks issac,, have seen this on http://benmarch.github.io/angular-ui-tour/#/docs, but i think they do it differently...

**Comment by isaacplmann** [comment]
The class should be set in version 2.0.0.

**Comment by fenta23** [comment]
will test it today.
