### ISSUE TITLE
No way to add custom button titles for each step

### ISSUE THREAD

**Issue by damo1884** [isaacplmann/ngx-tour#83]
Here is a PR to add the feature: https://github.com/isaacplmann/ngx-tour/pull/82

**Comment by isaacplmann** [comment]
Thanks for the PR!  I merged #82.  New version planned for today.

**Comment by isaacplmann** [comment]
Version 2.0.0 of all three plugins have been released.

**Comment by damo1884** [comment]
I am working on a no-ui framework version using ngx-popper

You can see the code here: https://github.com/damo1884/ngx-tour/tree/no-framework-ui

I followed the way you did it for NgxBootstrap

The issue I am having is that ngx-popper expects a `PopperContent` not a `TemplateRef`

`content: string | PopperContent;`

See: https://github.com/MrFrankel/ngx-popper/blob/master/src/popper-directive.ts 

I think it would be great to also have a demo that does not rely on a UI Framework but I am not sure if I should be following the NgxBootstrap way or the MatMenu way.

Any thoughts?

**Comment by damo1884** [comment]
Also did the custom button titles make it into the 2.0.0 release?

I just updated my dependencies and I don't see it there..

**Comment by isaacplmann** [comment]
1. I'd call it `ngx-tour-ngx-popper` instead of `ngx-tour-no-framework`, since you do have to use `ngx-popper`.

2. Get the version 2.0.0 of ngx-tour-ngx-bootstrap, it is written in a much cleaner and more maintainable way:

```
@Directive({ selector: '[tourAnchor]'})
export class TourAnchorNgxBootstrapPopoverDirective extends PopoverDirective {}

@Directive({
  selector: '[tourAnchor]',
})
export class TourAnchorNgxBootstrapDirective implements OnInit, OnDestroy, TourAnchorDirective {
  @Input() public tourAnchor: string;

  @HostBinding('class.touranchor--is-active')
  public isActive: boolean;

  constructor(private tourService: NgxbTourService,
              private tourStepTemplate: TourStepTemplateService,
              private element: ElementRef,
              @Host() private popoverDirective: TourAnchorNgxBootstrapPopoverDirective,
  ) {
  }
```

That way you don't have to include all the injected dependencies of the UI library in your extended version.

3. The `TemplateRef` is referenced in `tour-step-template.component.ts` and `tour-step-template.service.ts`.  You could make your own version use `<popper-content>` [here](https://github.com/damo1884/ngx-tour/blob/no-framework-ui/ngx-tour-ngx-no-framework/src/tour-step-template.component.ts#L11) and change all your references from `TemplateRef` to `PopperContent`.

4. Yes, custom button titles should be there.

**Comment by damo1884** [comment]
Awesome thanks for the feedback will try that out.

When I add this to my package.json

"ngx-tour-md-menu": "2.0.0"

I don't get the nextBtnTitle in IStepOption in V 2.0.0

**Comment by damo1884** [comment]
Ok I updated to V2.0.0 code and refactored 

I also renamed it from ngx-no-framework -> ngx-popper

See: https://github.com/damo1884/ngx-tour/tree/ngx-popper

The main issue I see is that PopperContent is not generic so it cannot take the IStepOption 

**This will not work:**
`public stepTemplate: PopperContent<{ step: IStepOption }>;`

**This is allowed but doesn't seem to work:**
`public stepTemplate: PopperContent;`

![image](https://user-images.githubusercontent.com/1332166/35831797-da0c9d80-0a7f-11e8-9ba5-65f2ff2cf66b.png)

I am really keen to get this working and I feel like I am really close but the tourStepTemplate is always undefined in showTourStep

![image](https://user-images.githubusercontent.com/1332166/35831901-26631718-0a80-11e8-8413-5eff0398d822.png)

Any ideas what might be the issue?

**Comment by damo1884** [comment]
Tried doing it the way md-menu is done and still the tourStepTemplate is still empty

**Comment by isaacplmann** [comment]
You want to remove the `<ng-template>` in the `tourStepTemplate.component.ts` and only have the `<popper-content>` component.  It's not getting picked up because it is "hidden" inside the template.

**Comment by damo1884** [comment]
I tried that but still its not being set.

https://github.com/damo1884/ngx-tour/commit/1fd59ff782204904e910f534fd8b20f9bec27167

If you could grab that fork a try run it yourself you might spot something I have missed.

I have already put a lot of effort into getting it to work but this last issue has me stumped.

I think a lot of people will want to have a no UI-Framework version that uses NgxPopper for popover placement and handling.

Maybe its just not possible with NgxPopper and I will have to find something else... :(

**Comment by isaacplmann** [comment]
I'm sure it's possible. I'll take a look tomorrow

**Comment by damo1884** [comment]
Hi Isaac,

Just checking back in to see if you had a chance to look at this at all?

It's 99% done and just the hookup to the TemplateRef is the road block.

I tried your suggestion above but that still didn't get me the TemplateRef/PopperContent in the code hooked up.

Anyway if you get a chance I owe you a beer!

Thanks
Damien

**Comment by isaacplmann** [comment]
I sent you a [PR](https://github.com/damo1884/ngx-tour/pull/2) on your repo yesterday.

**Comment by damo1884** [comment]
I didn't get an email about the PR sorry about that and thanks for taking a look at it.

I knew it was something trivial that was missing. (Initializing the popper as it seems)

**Comment by damo1884** [comment]
I have everything complete now except for one last issue with the Next/Prev buttons are always disabled.

> ![image](https://user-images.githubusercontent.com/1332166/36000174-f4fd6846-0cd6-11e8-9006-6e462f04bcb5.png)

I can see in the debugger that there are no steps loaded when it does the check.

![image](https://user-images.githubusercontent.com/1332166/36001454-2aa5471c-0cdb-11e8-8e82-5db8f5feee05.png)

When I debugged the loading of the steps everything is created as expected but then when hasNext() is called they are all gone.

So there must be some new TourService object getting assigned but I can't see how this is happening.

**Comment by damo1884** [comment]
Figured it out! I wasn't passing in the NgxpTourService I was passing the TourService in!

**Comment by isaacplmann** [comment]
Custom button titles have already been released.  Closing this issue.  More conversation about the ngx-popper PR can happen on #85 .
