### ISSUE TITLE
ng-bootstrap - Clicking on attached element.

### ISSUE THREAD

**Issue by headly48** [isaacplmann/ngx-tour#84]
When clicking on the element the ngBootstrap tour popover is attached to it closes the popup as it calls the toggle/close method on NgbPopover.

When clicking on the same element again it calls the show/toggle method on NgbPopover causing the popup to re appear but this time without the step being defined resulting in an empty popup.

This can be seen on the demo when it is attached to the header elements.

**Comment by isaacplmann** [comment]
I see this bug too.  I'll try to fix it soon.

**Comment by noamdeul** [comment]
any update about this issue?

Thanks!

**Comment by headly48** [comment]
Fixed this issue by creating my own TourAnchorDirective that overrides the NgbPopover close and toggle methods unfortunately haven't had time to properly do it and create a PR.

Make a copy of this file https://github.com/isaacplmann/ngx-tour/blob/master/ngx-tour-ng-bootstrap/src/tour-anchor.directive.ts and declare the directives in your module

Change 

@Directive({ selector: '[tourAnchor]' })
export class TourAnchorNgBootstrapPopoverDirective extends NgbPopover {}

TO

`
export class TourAnchorNgBootstrapPopoverDirective extends NgbPopover {
  private elementRef: ElementRef;

  constructor(_elementRef: ElementRef, _renderer: Renderer2, injector: Injector, componentFactoryResolver: ComponentFactoryResolver,
              viewContainerRef: ViewContainerRef, config: NgbPopoverConfig, ngZone: NgZone) {
    super(_elementRef, _renderer, injector, componentFactoryResolver, viewContainerRef, config, ngZone);
    this.elementRef = _elementRef;
    config.container = 'router-outlet';

  }

  close() {
    // Fix bug with popupbox closing
    super.close();
  }

  toggle() {
    // Fix bug with popupbox closing
  }
}
`

Also add these imports

`
import {
  ComponentFactoryResolver,
  Directive,
  ElementRef,
  Host,
  HostBinding,
  Injector,
  Input,
  NgZone,
  OnDestroy,
  OnInit,
  Renderer2,
  ViewContainerRef
} from '@angular/core';

import {NgbPopover, NgbPopoverConfig, Placement} from '@ng-bootstrap/ng-bootstrap';
`

And rename the directive/selector's otherwise you'll have a conflict

**Comment by isaacplmann** [comment]
@headly48 Thanks for providing the steps you took.  Is there anything I can do to help make it easier to submit a PR?

**Comment by noamdeul** [comment]
@headly48 thanks!!!
@isaacplmann - just change the directive according to @headly48 post.

**Comment by javieraviles** [comment]
I could not make it work...  It worked for you right @noamdeul ??

1) Do you need to copy both directives?
2) When you @headly48 said "And rename the directive/selector's otherwise you'll have a conflict", what do you mean exactly, changing both directive names and selectors? also changing it in the html then the way its triggered (tourAnchor)?

If it works for me I can do a PR, no problem...

Thanks in advance, I am actually getting a bit stuck here :)

**Comment by headly48** [comment]
Just raised a [PR](https://github.com/isaacplmann/ngx-tour/pull/109) for this issue 

@isaacplmann Could you please review the pr?

@javieraviles 
Pretty much, if you pull the directive into your project without changing the tag of the tourAnchor and   tourAnchor popover directives you'll encounter a tag conflict. Ie change [tourAnchor] to [walkthroughAnchor]  and in the html add it to an element with <div walkthroughAnchor="step-test">

**Comment by isaacplmann** [comment]
PR merged in ngx-tour-ng-bootstrap version 2.0.1.

**Comment by javieraviles** [comment]
Just updated to 2.0.1 and works great, thank you!!!
