### ISSUE TITLE
How to add tourAnchor to elements dynamically?

### ISSUE THREAD

**Issue by ranga-sriram** [isaacplmann/ngx-tour#87]
I have a use case where I need to add tourAnchor attribute to an element that comes in after a http request.  The element is within a *ngFor loop and add the attribute tourAnchor based upon a condition like this:
`[attr.tourAnchor]="i==0?'expand':null"`

The tourAnchor attribute shows up in html but it is not binding with the step mentioned for it.  The error shown is:
`Can't attach to unregistered anchor with id expand`

I tried re-initializing the steps again after the http request is completed within the subscribe block:
```
this.apiService.getJobsList(start, interval).subscribe(data => {
    this.tourService.initialize(steps);
});
```
This does not do the necessary binding.  Is there any other way to dynamically bind the elements to steps?

**Comment by isaacplmann** [comment]
The best way to add directives dynamically is to copy the host element and use an `*ngIf` directive.

So if you had this before:
```
<div *ngFor="let item of items">
<my-component [attr.tourAnchor]="i==0?'expand':null"></my-component>
</div>
```

You would change it to this:
```
<div *ngFor="let item of items">
<my-component  *ngIf="i==0" tourAnchor="expand"></my-component>
<my-component  *ngIf="i!=0"></my-component>
</div>
```

**Comment by ranga-sriram** [comment]
Thanks for your reply @isaacplmann . That works perfectly!  Just out of curiosity, would you know why the earlier approach would not work?

**Comment by isaacplmann** [comment]
I agree that would be nice.  Unfortunately, Angular doesn't work that way.  In order for AoT compilation to work, the compiler needs to know up front whether a directive will be applied to an element.  `[attr.tourAnchor]` just means apply the html attribute `tourAnchor` to this element, but that happens after the compiler has looked through your templates for selectors that match directives.

You can dynamically create a component using `ComponentFactoryResolver` and some manual code to wire things up, but I haven't found any way to dynamically add a directive to an existing element/component.

**Comment by ranga-sriram** [comment]
Thanks for your explanation @isaacplmann

**Comment by adripanico** [comment]
Why not

    <div *ngFor="let item of items; let i = index">
      <my-component  [tourAnchor]=" i=== 0 ? 'expand' : undefined"></my-component>
    </div>

?

**Comment by vanderkorn** [comment]
You can generate unique step ID, but don't use it

For example:

`[tourAnchor]="i === 0 ? 'expand' : 'uniqueFakeStepId_' + i" `
