### ISSUE TITLE
ngx-tour-core npm package not updated to latest code - current latest version is 3 months old

### ISSUE THREAD

**Issue by damo1884** [isaacplmann/ngx-tour#88]
https://www.npmjs.com/package/ngx-tour-core

The custom button titles is still missing from the current latest version of ngx-tour-core 2.0.0

**Comment by isaacplmann** [comment]
ngx-tour-core@2.1.0 has been published.

**Comment by damo1884** [comment]
Should we also need to update the package.json in the sub projects that rely on it?

https://github.com/isaacplmann/ngx-tour/blob/master/ngx-tour-console/package.json
https://github.com/isaacplmann/ngx-tour/blob/master/ngx-tour-ngx-popper/package.json
https://github.com/isaacplmann/ngx-tour/blob/master/ngx-tour-ngx-bootstrap/package.json
https://github.com/isaacplmann/ngx-tour/blob/master/ngx-tour-ng-bootstrap/package.json
https://github.com/isaacplmann/ngx-tour/blob/master/ngx-tour-md-menu/package.json

I can create a PR if that would be easier?

**Comment by isaacplmann** [comment]
Yes. We'll need to do that. I already did for ngx-popper. PR is welcome

**Comment by damo1884** [comment]
https://github.com/isaacplmann/ngx-tour/pull/89

**Comment by damo1884** [comment]
Do you have to redeploy each of the npm packages every time there is a code change?

**Comment by isaacplmann** [comment]
Yes, I update the version number and the changelog and then publish them to npm.
