### ISSUE TITLE
Using ngx-tour with Material Dialog

### ISSUE THREAD

**Issue by matthew-alpin** [isaacplmann/ngx-tour#90]
When navigating to a route that opens a Material Dialog, the tour anchor is not registered with ngx-tour yet, so it warns that

`Can't attach to unregistered anchor with id ...`

and doesn't open the tour step. Any ideas on how to avoid this problem? Is there a way to pre-register anchors in dialogs? Or is there another feature of ngx-tour that I'm missing?

Amazing library, thanks for your help.

**Comment by isaacplmann** [comment]
That's a usecase I hadn't thought of, and I can't think of a good solution for it with the library in its current state.  Perhaps this could be solved in a refactor that would remove the hard-coupling to the RouterModule.  Some way for the app developer to provide their own observable/promise that tells the TourService when to try to open the next step.

Or I could tackle it by registering the intent to open a step and just wait for the step to be registered to open it.

I need to think about this more.

**Comment by matthew-alpin** [comment]
Sounds like there's some interesting opportunities for improvement here. Thanks for the quick reply. We'll keep an eye out for a new version with the refactor / ability to support this usecase.

**Comment by matthew-alpin** [comment]
HI @isaacplmann, do you by chance have any news on this?

**Comment by isaacplmann** [comment]
Nope. I'd like to work on this but haven't found time.  I can coach you through a PR if you want to tackle it.
