### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by esbrito** [isaacplmann/ngx-tour#93]
Hi,
when I initialize the service I keep getting an error.
Here is the initialization in a component I have:
`this.tourService.initialize([{
            anchorId: 'some.anchor.id',
            content: 'Some content',
            title: 'First',
          },{
            anchorId: 'other.anchor.id',
            content: 'other content',
            title: 'Second',
          }]);` 
Here is the error I get:
![image](https://user-images.githubusercontent.com/19297675/36574424-885b56b8-1824-11e8-931a-2a771f96b03f.png)

Apparently the problem is in this line:
`          <button mat-icon-button [disabled]="!tourService.hasNext(step)" (click)="tourService.next()">
`
I dont even need to start the Tour to get the error, just initialize it

Any thoughts?

Thanks :)

**Comment by isaacplmann** [comment]
Where is the `<button>` code? Is that inside the `<tour-step-template>`?

**Comment by esbrito** [comment]
Its from ng:///TourMatMenuModule/TourStepTemplateComponent.html

**Comment by esbrito** [comment]
Got it working. Ive just moved the initialization to the right component (app.component.ts) and imported TourMatMenuModule  in every module involved in the Tour. Thanks and sorry for the inconvenience.
