### ISSUE TITLE
NgBootstrap is not working in angular-cli v 1.4.6 with ng 4

### ISSUE THREAD

**Issue by ng-model** [isaacplmann/ngx-tour#94]
During debugging the this.anchors is always coming as empty Object in next step function.

![image](https://user-images.githubusercontent.com/11791070/36710359-6893a400-1b4b-11e8-8671-cc49f2ed9b82.png)

![image](https://user-images.githubusercontent.com/11791070/36710397-b4c3f7b2-1b4b-11e8-9fb8-230b052f0125.png)

**Comment by isaacplmann** [comment]
That would happen if the `tourAnchor` directives haven't been rendered on the screen yet, or if they are registering themselves with a different `TourService` for some reason.

Try this and see if the `tourAnchor`s are being registered:

```ts
this.tourService.anchorRegister$.subscribe(x => console.log(x));
```

**Comment by madurimanoj** [comment]
Events are not registered, with the above service nothing is printing in a console. Service initialization is hapennning , which was there in the screenshot-1 . What may be the reason that registering is not happening?

**Comment by isaacplmann** [comment]
Have you included `tourAnchor="start"` in some component that is rendered on the page?

Are you importing `NgxTourNgBootstrap.forRoot()` in more than one module?
