### ISSUE TITLE
How to get the gray background around the anchor element?

### ISSUE THREAD

**Issue by Badhumvee** [isaacplmann/ngx-tour#97]
Hi Isaacplmann,

I really like this module and would like to implement it if it can do the gray background around the anchor element.  I could not find that in the documentation.   I am new to angular so if you could please help me understand how I can make it work with angular4(and soon to be angular5) web app using angular.material.io design?   If you have a demo of the gray  background working for angular5/4 that would be really appreciated.  

Thanks a lot.

**Comment by isaacplmann** [comment]
You can have a backdrop behind the tour pretty easily [like this](https://github.com/isaacplmann/ngx-tour/issues/61#issuecomment-345786088).

Greying out everything except the currently active tourAnchor is more difficult.  There is a `.touranchor--is-active` class applied to the currently active tourAnchor element, which you could use to apply your own styles.

You could try something like this, but it won't look great if the tourAnchor is applied to an inline element.

```
.touranchor--is-active {
    position: relative;
    z-index: 10000;
}

.cdk-overlay-transparent-backdrop, .cdk-overlay-transparent-backdrop.cdk-overlay-backdrop-showing {
    opacity: 0.5;
    background: black;
}
```

**Comment by isaacplmann** [comment]
If you really want to have the `.touranchor--is-active` element above the backdrop, you'll need to somehow clone it in the DOM and raise the clone above the backdrop.  FYI, the default z-index for the `.cdk-overlay-backdrop` is 1000.

Cloning the DOM has a whole bunch of pitfalls and weird edge cases, so I'm not planning to support that in this library.  I believe that's what [angular-ui-tour](http://benmarch.github.io/angular-ui-tour/#/docs) did for AngularJS.

**Comment by jkon** [comment]
Yeah, I don't think I want to deal with cloning the DOM, but I just don't understand why setting the z-index on .touranchor--is-active to over 1000 (or whatever the backdrop is set to) isn't working. In the dev console in chrome, I can't change it to any number that will get it on top.

**Comment by hakimio** [comment]
@jkon z-index works just fine, but you might also have to set background to white or some other color for you to see the result.

**Comment by isaacplmann** [comment]
Check out ngx-tour-md-menu@3.1.0 with the `enableBackdrop` feature.

**Comment by jkon** [comment]
@isaacplmann I installed 3.1.0 and now I am getting an error saying 
No component factory found for TourAnchorOpenerComponent. Did you add it to @NgModule.entryComponents?
If I try to add it to the entry components, I get an error saying it can't be an entry component

**Comment by isaacplmann** [comment]
@jkon Are you importing the `TourMatMenuModule`? Are you using the `TourService` from `ngx-tour-md-menu` and not from `ngx-tour-core`?

**Comment by jkon** [comment]
I was using the TourService from core. Thanks! However, enableBackdrop doesn't work quite right. It does add the backdrop and the anchor element is above the backdrop, but it isn't showing up above everything. I had a similar problem with ngx-smart-modal. But to fix that issue, I had to move the modals I was using up to a higher level in the app and open them from the lower levels. But I'm not sure how to make a similar fix in this case. I may just not be able to use the backdrop feature for my app

**Comment by isaacplmann** [comment]
Can you inspect your DOM with the backdrop enabled and let me know if increasing the z-index solves your problem?

![image](https://user-images.githubusercontent.com/861504/44550360-facf0300-a6f1-11e8-8952-91596f2bbf6d.png)

Right now there isn't a class on that backdrop element, but if changes the z-index solves your problem, I'll add a class so you can customize it.

**Comment by jkon** [comment]
It does seem to help. I have a lot of z-indexing in my app because of various reasons. a class to customize how high up the backdrop goes would be great

**Comment by isaacplmann** [comment]
3.1.1 published.  Let me know if that fixes it for you

**Comment by jkon** [comment]
that works perfect. Thanks for the super quick turnaround!

**Comment by thari119** [comment]
the touranchor class is not getting added to my components. i'm using ngx bootstrap. can you please advice on this?

**Comment by hakimio** [comment]
@thari119 class "touranchor--is-active" should be set because of the [HostBinding](https://github.com/isaacplmann/ngx-tour/blob/aa3610839445849797bbca4bbd26f2cd8eb9c55f/projects/ngx-tour-ngx-bootstrap/src/lib/tour-anchor.directive.ts#L18).

**Comment by thari119** [comment]
@hakimio hey check the attached image. this is when the tour is active and is showing to the menu item i want. but as u can see the touranchor class is not added 

<img width="466" alt="screenshot 2018-12-06 at 1 38 42 pm" src="https://user-images.githubusercontent.com/37997923/49563821-5600ca80-f95c-11e8-910e-440a4c562275.png">

**Comment by isaacplmann** [comment]
@thari119 Is that component using OnPush change detection?  That's the only thing I can think of that might cause this.  Are you using `ngx-tour-ngx-bootstrap@2.0.0` or higher?
