### ISSUE TITLE
Can't attach to unregistered anchor with id list

### ISSUE THREAD

**Issue by 2rhop** [isaacplmann/ngx-tour#99]
## I am following the steps writed in the [page](https://isaacplmann.github.io/ngx-tour/)

1. Add <tour-step-template></tour-step-template> to your root app component
2. Define anchor points for the tour steps by adding the tourAnchor directive throughout your app.
`<div tourAnchor="some.anchor.id">...</div>`
3. Define your tour steps using tourService.initialize(steps)
```
this.tourService.initialize([{
  anchorId: 'some.anchor.id',
  content: 'Some content',
  title: 'First',
}, {
  anchorId: 'another.anchor.id',
  content: 'Other content',
  title: 'Second',
}]);
```
4. Start the tour with `tourService.start()`
5. Check out the demo source code for an example.

> ## Why i get the error Can't attach to unregistered anchor with id _myId_

**Comment by joffreymaz** [comment]
I'm having the same issue here, did you find any solution ?

**Comment by bluefire2121** [comment]
Likewise. How do you use the tour to move across components on a single route?

**Comment by bluefire2121** [comment]
Solved my issue by referring to #65 👍 :-)

**Comment by sunarasim** [comment]
I was getting the same error "Can't attach to unregistered anchor with id". After through investigation, i realized we had some components and directives using TourServce from ngx-tour and Ngx-popper-tour-service from Ngx-tour-ngx-popper. Fixed them by locally adding the files from GitHub and updating them to use the Ngx-popper-tour-service solved the issue.

**Comment by swap1108** [comment]
This one worked for me 
Change in your component.ts file:
`import { TourService } from "ngx-tour-core";`
to
`import { TourService } from "ngx-tour-md-menu";`
Src:[https://github.com/isaacplmann/ngx-tour/issues/32#issuecomment-321278752](url)

**Comment by chirag921** [comment]
> single

Did you find any answer?
